src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>AMC_Type__c</fullName>
        <label>AMC Type</label>
        <picklist>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <label>Product Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_ActivateContractCtrl.cls
@isTest
public class Test_ActivateContractCtrl{
    private static testMethod void unitTestActivateContractCtrl(){
        Account Acc = new Account();
        Acc.Name = 'TestComp';
        acc.Customer_ID__c = 'ACC-1001';
        Insert Acc;
        
        Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        Prod.CurrencyIsoCode = 'INR';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        Contracts__c Con = new Contracts__c();
        Con.Products__c = Prod.Id;
        Con.AMC_Type__c = 'Comprehensive';
        Con.Account_Name__c  = Acc.Id;
        Con.Product_Quantity__c = 100;
        Insert Con;
        
        ApexPages.StandardController cont = new ApexPages.StandardController(con);
        ActivateContractCtrl actCOn = new ActivateContractCtrl(cont);
        actCOn .updateContract();
        
        Contracts__c contra = new Contracts__c();
        //contra = [Select id , Status__c from Contracts__c where id=:Con.id] ;
        //system.assertEquals('Activated',contra.Status__c);
    }
}