src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <formula>City__r.Branch__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>City__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <label>Category Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_PM__c</fullName>
        <label>No. Of PM</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>COMPONENT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <formula>Account__r.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON-LINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>$User.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <formula>Service_Engineer_Assigned__r.Service_Engineer_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Engineer Id</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DESIGNATION__c</fullName>
        <label>Designation</label>
        <picklist>
            <picklistValues>
                <fullName>AREA SERVICE IN-CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AREA SERVICE IN-CHARGE (BATTERY)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT VICE PRESIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRANCH SERVICE IN-CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPUTY GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPUTY MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELECTRICIAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENGINEER - TESTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE - AUDIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE - CALL CENTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELPER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REGIONAL SERVICE MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REGIONAL TRAINING SPECILIEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE COORDINATOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - GEN SET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - HIGH CAPACITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - LOW CAPACITY</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - TRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - WAREHOUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. EXECUTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. VICE PRESIDENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Center_Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <inlineHelpText>Required Field . Should match Oracle AR Customer Number</inlineHelpText>
        <label>Service Engineer Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/testOpenServiceRequest.cls
@isTest
public class testOpenServiceRequest{
    private static testMethod void TestForOpenServiceRequest(){
        //User u = [Select Id from user where profile.name = 'Call Center' and IsActive = true limit 1];
        
         User u = new User(
             Alias =  'alia', 
             Email = 'test@sk.com',
             EmailEncodingKey = 'UTF-8', 
             LanguageLocaleKey = 'en_US', 
             LocalesIdKey = 'en_US', 
             TimeZonesIdKey = 'America/Los_Angeles',
             Username = 'test@sk.com',
             LastName = 'lname',
             CommunityNickname = 'cname',
             Stock_Point__c = '033-',
             ProfileId = [select id, Name from Profile where Name = 'System Administrator'].id
         );  
      System.runAs(u) {  
        /*Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        Prod.CurrencyIsoCode = 'INR';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;*/
        
        Product__c Prod = new Product__c();
        Prod.name = 'Test1';
        Prod.Product_Code__c = '12345';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Prod.CurrencyIsoCode = null;
        Prod.Product_Category__c = 'UPS';
        Prod.Category_Code__c = 'Cat';
        Prod.OwnerId = u.id;
        Prod.No_Of_PM__c = '4';
        insert Prod;
        
         Price_Books__c objPB = new Price_Books__c();
             objPB.Name='Standard Price Book';
             insert objPB;
         
       Price_Book_Entry__c objPBE =new Price_Book_Entry__c();
       objPBE.Product__c=Prod.id;
       objPBE.Price_Book__c=objPB.id;
       objPBE.UnitPrice__c=200;
       insert objPBE;
        
        
       Account acct = new Account(
        name = 'test',
        Customer_ID__c = '0007'
        );
        insert acct; 
    
       Contact cont = new Contact(
            LastName = 'Test Contact1',
            phone = '01122120767',
            MobilePhone = '09988899888',
            email = 'a@b.com',
            AccountId = acct.Id
        );
        
        insert cont;
        
         Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
        Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Engineer');
        Id stockId = rtByName.getRecordTypeId();
        Stock_Point__c objSP = new Stock_Point__c();
          objSP.RecordTypeId = stockId;
          objSP.OwnerId = u.Id;
          objSP.Name = 'XYZ';
          objSP.Service_Center_Description__c = 'TestCenter1';
          objSP.Service_Center_Address__c = 'Address1';
          objSP.Service_Center_Location_Code__c = '033-';
          objSP.DESIGNATION__c = 'HELPER';
          objSP.Service_Engineer_Id__c = 'H900113';
          objSP.Region__c = 'CENTRAL';
          objSP.Branch__c ='LUCKNOW';
          objSP.Active__c = true;
          insert objSP;
        
        Service_Request__c Cas1 = new Service_Request__c();
        Cas1.Origin__c = 'Email';
        Cas1.Contact__c = cont.id;
        Cas1.Product_Serial_No__c = '1001';
        Cas1.Service_Charge_Type__c = 'Visit';
        Cas1.Products__c = Prod.Id;
        Cas1.OwnerId = u.id;
        Cas1.Type_of_Service_Request__c = 'Others';
        Cas1.Status__c = 'New';
        Cas1.AMC_Status__c = 'Yes';
        //Cas1.Product_Code__c = con.Product_Serial_No__c ;
        Cas1.Product_Category__c = 'BATTERY';
        Cas1.Warranty_Status__c = 'No';
        Cas1.Reason__c = 'Reason';
        Cas1.Account__c = acct.id ;
        Cas1.PROBLEM_OBSERVED__c = 'FUSE BROKEN';
        Cas1.Service_Engineer_Assigned__c = objSP.id;
        Cas1.Agent_Name__c = 'MAMTA';
        Cas1.ClosedDate__c = system.today();
        Insert Cas1;
        ApexPages.currentPage().getParameters().put('id',cas1.id);
        ApexPages.StandardController con = new ApexPages.StandardController(cas1);
        OpenServiceRequest csr = new OpenServiceRequest(con);
        
        csr.srObj.Completion_Date_Time__c = system.now();
        csr.srObj.Attended_Date_Time__c =  system.now();   
        csr.srObj.Reason__c =  'SYSTEM DEAD';  
        csr.srObj.Service_Type__c = 'LOCAL - ON SITE';
        csr.srObj.CALL_TYPE__c = 'COMPLAIN END USER';
        csr.srObj.Preferred_Date_for_Visit__c = Date.Today();
        csr.srObj.Warranty_Status__c = 'No';
        csr.srObj.Product_Serial_No__c = '1001';//'PKG-FM-048';
        csr.srObj.Service_Engineer_Assigned__c = objSP.id;
        
        csr.getOptions();
        csr.SelectedStatus = 'ReOpen';
        csr.doSave();
        csr.doCancel();
        Service_Request__c Cas = new Service_Request__c();
        Cas = [Select id, Status__c from Service_Request__c where id=:Cas1.id];
        //system.assertEquals('Closed', cas.Status__c);       
    }
}
}