src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <formula>TEXT( City__r.Local_Upcountry__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Attended_Date_Time__c</fullName>
        <label>Attended Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CALL_TYPE__c</fullName>
        <description>FOR DIFFERENTIATE SERVICE REQUEST.</description>
        <label>Call Type</label>
        <picklist>
            <controllingField>Complain_Type__c</controllingField>
            <picklistValues>
                <fullName>COMPLAIN END USER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPLAIN DEALER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRC REPAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM VISIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENERAL VISIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT SALE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FREE SERVICE CAMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPANY STOCK SET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEALER STOCK SET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Completion_Date_Time__c</fullName>
        <label>Completion Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <formula>Account__r.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Date_for_Visit__c</fullName>
        <description>Here we put in the Customer&apos;s preffered Date of Visit by Service Engineer. By Default the value is Case Created Date</description>
        <label>Appointment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON MAINS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAINS MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BLOWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BROKEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWITCH FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM ON BUT NO OUTPUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM DEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS LOW BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER LOAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS SHORT CIRCUIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING CONTINUSELY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT CHARGING BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY OVERHEATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY DRY RUN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONNECTOR BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSIT DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSFORMER BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARD BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANGEOVER PROBLEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAN NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOOSE CONNECTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOCKET DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAIN LEAD FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED DISPLAY NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER TEMPERATURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY LOW BACKUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM GENERATES HUMMING SOUND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Type__c</fullName>
        <label>Service Charge Type</label>
        <picklist>
            <controllingField>AMC_Status__c</controllingField>
            <picklistValues>
                <fullName>Carry In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <picklist>
            <controllingField>CALL_TYPE__c</controllingField>
            <picklistValues>
                <fullName>LOCAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPCOUNTRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARRY IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Service_Request__c</fullName>
        <label>Type of Service Request</label>
        <picklist>
            <controllingField>Warranty_Status__c</controllingField>
            <picklistValues>
                <fullName>Sale of Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testCloseServiceRequestCon.cls
@isTest
public class testCloseServiceRequestCon{
    private static testMethod void myUnitTestForCloseServiceRequest(){
        User u = [Select Id from user where profile.name = 'Service Center' and IsActive = true limit 1];
        
        Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        Prod.CurrencyIsoCode = 'INR';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        
       Account acct = new Account(
        name = 'test',
        Customer_ID__c = '0007'
        );
        insert acct; 
    
       Contact cont = new Contact(
            LastName = 'Test Contact1',
            phone = '01122120767',
            MobilePhone = '09988899888',
            email = 'a@b.com',
            AccountId = acct.Id
        );
        
        insert cont;
        
        Service_Request__c Cas1 = new Service_Request__c();
        Cas1.Origin__c = 'Email';
        Cas1.Contact__c = cont.id;
        Cas1.Product_Serial_No__c = '0101';
        Cas1.Service_Charge_Type__c = 'Visit';
        Cas1.Products__c = Prod.Id;
        Cas1.OwnerId = u.id;
        Cas1.Type_of_Service_Request__c = 'Others';
        Insert Cas1;
        ApexPages.currentPage().getParameters().put('id',cas1.id);
        ApexPages.StandardController con = new ApexPages.StandardController(cas1);
        CloseServiceRequestCon csr = new CloseServiceRequestCon(con);
        
        csr.srObj.Completion_Date_Time__c = system.now();
        csr.srObj.Attended_Date_Time__c =  system.now();   
        csr.srObj.Reason__c =  'SYSTEM DEAD';  
        csr.srObj.Service_Type__c = 'LOCAL - ON SITE';
        csr.srObj.CALL_TYPE__c = 'COMPLAIN END USER';
        csr.srObj.Preferred_Date_for_Visit__c = Date.Today();
        csr.srObj.Warranty_Status__c = 'No';
        csr.getOptions();
        csr.SelectedStatus = 'Closed';
        csr.doSave();
        csr.doCancel();
        Service_Request__c Cas = new Service_Request__c();
        Cas = [Select id, Status__c from Service_Request__c where id=:Cas1.id];
        //system.assertEquals('Closed', cas.Status__c);       
    }

}