src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CALL_TYPE__c</fullName>
        <description>FOR DIFFERENTIATE SERVICE REQUEST.</description>
        <label>Call Type</label>
        <picklist>
            <picklistValues>
                <fullName>COMPLAIN END USER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPLAIN DEALER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRC REPAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM VISIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENERAL VISIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WARE HOUSE REPAIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FREE SERVICE CAMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT SALE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <formula>Account.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Date_for_Visit__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <description>Here we put in the Customer&apos;s preffered Date of Visit by Service Engineer. By Default the value is Case Created Date</description>
        <label>Preferred Date for Visit</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOME UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON-LINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>R00N20000001R8w3EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>COMPONENT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_MapCaseToCustom.cls
@isTest
public class Test_MapCaseToCustom {
    
    private static testMethod void myUnitTest(){
      
      
    Account acc = new Account(
        name = 'test',
        Customer_ID__c = 'ACC-1001'
        );
        insert acc; 
   

    Contact con = new Contact(
            LastName = 'Test Contact1',
            phone = '01122120767',
            email = 'a@b.com',
            AccountId = acc.id
            );
        insert con;
        
        Product__c Prod1 = new Product__c();
        Prod1.name = 'Testt1';
        Prod1.Product_Code__c = '10022';
        Prod1.Is_Active__c = True;
        Prod1.UoM__c = 'Set';
        Insert Prod1; 
        
      
       Case cas = new Case(
           AccountId = acc.id,
           ContactId = con.id,
           Origin = 'Email',
           Priority='P1',
           Status = 'Assigned',
           CALL_TYPE__c = 'COMPLAIN END USER',
           Reason = 'SYSTEM NOT WORKING ON MAINS',
           Warranty_Status__c = 'Yes',
           Preferred_Date_for_Visit__c = Date.today(),
           Product_Category__c = 'BATTERY',
           CurrencyIsoCode  = 'INR'
      );
       insert cas; 
       update cas;
       system.assert(cas.id != null);
    }    
}