src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <label>Mobile No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ANDHRA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANDIGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUNCHAL PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHATTISGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DADRA &amp; NAGAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAMAN &amp; DIU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HARYANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIMACHAL PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAMMU &amp; KASHMIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JHARKHAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GUJRAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KARNATAKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KERALA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANIPUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEGHALAYA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MADHYA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAHARASHTRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORISSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEW DELHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIZORAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAGALAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUNJAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAMIL NADU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIPURA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAJASTHAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIKKIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PONDICHERRY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attended_Date_Time__c</fullName>
        <label>Attended Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CALL_SUB_STATUS__c</fullName>
        <label>CALL SUB STATUS</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>PART PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO POWER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOOR LOCK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUSTOMER NOT AVAILABLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFER TO TRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING FOR PJP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TECHANICAL PROBLEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING FOR REPLACEMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPROVAL ON HOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPROVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISAPPROVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WRONG ADDRESS/ INVALID CONTACT No.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER BRAND PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUSTOMER REFUSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DUPLICATE CALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHERS-PENDING</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ClosedDate__c</fullName>
        <label>Date/Time Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Completion_Date_Time__c</fullName>
        <label>Completion Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <formula>Account__r.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSR_No__c</fullName>
        <externalId>true</externalId>
        <label>FSR No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Date_for_Visit__c</fullName>
        <description>Here we put in the Customer&apos;s preffered Date of Visit by Service Engineer. By Default the value is Case Created Date</description>
        <label>Appointment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Type__c</fullName>
        <label>Service Charge Type</label>
        <picklist>
            <controllingField>AMC_Status__c</controllingField>
            <picklistValues>
                <fullName>Carry In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status_Remark__c</fullName>
        <label>Sub Status Remark</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Service_Request__c</fullName>
        <label>Type of Service Request</label>
        <picklist>
            <controllingField>Warranty_Status__c</controllingField>
            <picklistValues>
                <fullName>Sale of Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/searchenginecontroller_Test.cls
@isTest
 public with sharing class searchenginecontroller_Test {
     private static testMethod void searchEngineTestMethod(){

        Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        Prod.CurrencyIsoCode = 'INR';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        Account acct = new Account(
        name = 'test',
        Customer_ID__c = '0007'
        );
        insert acct;        
        
     Service_Request__c Cas1 = new Service_Request__c();
        Cas1.Origin__c = 'Email';
        Cas1.Account__c = acct.id;
        Cas1.Product_Serial_No__c = '0101';
        Cas1.Service_Charge_Type__c = 'Visit';
        Cas1.Products__c = Prod.Id;
        Cas1.FSR_No__c = '12345';
        Cas1.Type_of_Service_Request__c = 'Others';
        Cas1.Status__c ='New';
       
      
    Service_Request__c Cas2 = new Service_Request__c();
        Cas2.Origin__c = 'Email';
        cas2.Account__c = acct.id;
        cas2.Product_Serial_No__c = '0101';
        cas2.Service_Charge_Type__c = 'Visit';
        cas2.Products__c = Prod.Id;
        cas2.FSR_No__c = '56789';
        cas2.Type_of_Service_Request__c = 'Others';
        cas2.Status__c ='Pending';
        cas2.CALL_SUB_STATUS__c ='Part Pending';
        cas2.Sub_Status_Remark__c ='abcd';
            
   Service_Request__c cas3 = new Service_Request__c();
        cas3.Origin__c = 'Email';
        cas3.Account__c = acct.id;
        cas3.Product_Serial_No__c = '0101';
        cas3.Service_Charge_Type__c = 'Visit';
        cas3.Products__c = Prod.Id;
        cas3.FSR_No__c = '1010101';
        cas3.Type_of_Service_Request__c = 'Others';
        cas3.Status__c ='Pending';
        cas3.CALL_SUB_STATUS__c ='DOOR LOCKED';
        cas3.Sub_Status_Remark__c ='efgh';
        
        
   Service_Request__c cas4 = new Service_Request__c();
        cas4.Origin__c = 'Email';
        cas4.Account__c = acct.id;
        cas4.Product_Serial_No__c = '0101';
        cas4.Service_Charge_Type__c = 'Visit';
        cas4.Products__c = Prod.Id;
        cas4.FSR_No__c = '101345';
        cas4.Type_of_Service_Request__c = 'Others';
        cas4.Status__c ='Pending';
        cas4.CALL_SUB_STATUS__c ='NO POWER';
        cas4.Sub_Status_Remark__c ='ijkl';    
        
    Service_Request__c cas5 = new Service_Request__c();
        cas5.Origin__c = 'Email';
        cas5.Account__c = acct.id;
        cas5.Product_Serial_No__c = '0101';
        cas5.Service_Charge_Type__c = 'Visit';
        cas5.Products__c = Prod.Id;
        cas5.FSR_No__c = '101678';
        cas5.Type_of_Service_Request__c = 'Others';
        cas5.Status__c ='Pending';
        cas5.CALL_SUB_STATUS__c ='CUSTOMER NOT AVAILBLE';
        cas5.Sub_Status_Remark__c ='mnop';           
        
     Service_Request__c cas6 = new Service_Request__c();
        cas6.Origin__c = 'Email';
        cas6.Account__c = acct.id;
        cas6.Product_Serial_No__c = '0101';
        cas6.Service_Charge_Type__c = 'Visit';
        cas6.Products__c = Prod.Id;
        cas6.FSR_No__c = '101456';
        cas6.Type_of_Service_Request__c = 'Others';
        cas6.Status__c ='Pending';
        cas6.CALL_SUB_STATUS__c ='REFER TO TRC';
        cas6.Sub_Status_Remark__c ='qrst';   
        
     Service_Request__c cas7 = new Service_Request__c();
        cas7.Origin__c = 'Email';
        cas7.Account__c = acct.id;
        cas7.Product_Serial_No__c = '0101';
        cas7.Service_Charge_Type__c = 'Visit';
        cas7.Products__c = Prod.Id;
        cas7.FSR_No__c = '23456';
        cas7.Type_of_Service_Request__c = 'Others';
        cas7.Status__c ='Pending';
        cas7.CALL_SUB_STATUS__c ='PENDING FOR PJP';
        cas7.Sub_Status_Remark__c ='acgd';        
      
      Service_Request__c cas8 = new Service_Request__c();
        cas8.Origin__c = 'Email';
        cas8.Account__c = acct.id;
        cas8.Product_Serial_No__c = '0101';
        cas8.Service_Charge_Type__c = 'Visit';
        cas8.Products__c = Prod.Id;
        cas8.FSR_No__c = '8765';
        cas8.Type_of_Service_Request__c = 'Others';
        cas8.Status__c ='Pending';
        cas8.CALL_SUB_STATUS__c ='TECHANICAL PROBLEM';
        cas8.Sub_Status_Remark__c ='kjhg';
        
      Service_Request__c cas9 = new Service_Request__c();
        cas9.Origin__c = 'Email';
        cas9.Account__c = acct.id;
        cas9.Product_Serial_No__c = '0101';
        cas9.Service_Charge_Type__c = 'Visit';
        cas9.Products__c = Prod.Id;
        cas9.FSR_No__c = '678967';
        cas9.Type_of_Service_Request__c = 'Others';
        cas9.Status__c ='Pending';
        cas9.CALL_SUB_STATUS__c ='PENDING FOR REPLACEMENT';
        cas9.Sub_Status_Remark__c ='ghyt';  
        
      Service_Request__c cas10 = new Service_Request__c();
        cas10.Origin__c = 'Email';
        cas10.Account__c = acct.id;
        cas10.Product_Serial_No__c = '0101';
        cas10.Service_Charge_Type__c = 'Visit';
        cas10.Products__c = Prod.Id;
        cas10.FSR_No__c = '34566';
        cas10.Type_of_Service_Request__c = 'Others';
        cas10.Status__c ='Pending';
        cas10.CALL_SUB_STATUS__c ='APPROVAL ON HOLD';
        cas10.Sub_Status_Remark__c ='ghyt';     
          
List<Service_Request__c > srList = new List<Service_Request__c>();
srList.add(Cas1);
srList.add(Cas2);
srList.add(Cas3);
srList.add(Cas4);
srList.add(Cas5);
srList.add(Cas6);
srList.add(Cas7);
srList.add(Cas8);
srList.add(Cas9);
srList.add(Cas10);

insert srList;

apexPages.currentPage().getParameters().put('selectedStatus', 'New');
apexPages.currentPage().getParameters().put('selectedSubStatus', 'Part Pending');
//Create instance of class here and then start calling method.
searchenginecontroller objSrchClass = new searchenginecontroller();
objSrchClass.getCounts();
objSrchClass.refreshSearchResult();
objSrchClass.refreshSearchResult1();
objSrchClass.getRecordCount();
objSrchClass.SearchResult();

objSrchClass.fromSR.Preferred_Date_for_Visit__c   = System.Today();
objSrchClass.ToSR.Preferred_Date_for_Visit__c   = System.Today();

objSrchClass.fromSR.Created_Date__c = System.Today();
objSrchClass.ToSR.Created_Date__c = System.Today(); 

objSrchClass.fromSR.Attended_Date_Time__c = System.Today();
objSrchClass.ToSR.Attended_Date_Time__c = System.Today(); 

objSrchClass.fromSR.Completion_Date_Time__c = System.Today();
objSrchClass.ToSR.Completion_Date_Time__c = System.Today(); 

objSrchClass.fromSR.ClosedDate__c = System.Today();
objSrchClass.ToSR.ClosedDate__c = System.Today(); 

//objSrchClass.thisAccount.Mobile_No__c = '1234567890;
objSrchClass.thisAccount.State__c = 'Delhi';
objSrchClass.thisAccount.District__c= 'Delhi';


objSrchClass.thisProduct.Product_Code__c = 'Product';

objSrchClass.fromSr.Product_Category__c = 'Battery';
objSrchClass.fromSr.Group__c = 'Group1' ;
objSrchClass.fromSr.Sub_Group__c =  'Group2' ;
objSrchClass.fromSr.Category__c  = 'thiscategory';
objSrchClass.fromSr.Status__c= 'thiscategory';
objSrchClass.fromSr.Complain_Type__c = 'thiscategory';
objSrchClass.fromSr.Service_Type__c = 'thiscategory';
objSrchClass.fromSr.CALL_TYPE__c = 'thiscategory';
objSrchClass.fromSr.Product_Serial_No__c= '1234';
objSrchClass.fromSr.PROBLEM_OBSERVED__c = 'thisproblem';
objSrchClass.fromSr.CALL_SUB_STATUS__c = 'thissubstatus';
objSrchClass.fromSr.Warranty_Status__c = 'yes';

objSrchClass.SearchResult();
     }
}