src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AMC_Created__c</fullName>
        <label>AMC Created</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AMC_Type__c</fullName>
        <label>AMC Type</label>
        <picklist>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Comprehensive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>R00N20000001R8w3EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Bill_No__c</fullName>
        <label>Service Bill No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Type__c</fullName>
        <label>Service Charge Type</label>
        <picklist>
            <controllingField>AMC_Status__c</controllingField>
            <picklistValues>
                <fullName>Carry In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Engineer Assigned</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>R00N20000001R8wrEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <formula>Service_Engineer_Assigned__r.Service_Engineer_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Engineer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Name__c</fullName>
        <label>Service Engineer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_in_Hand__c</fullName>
        <label>Defective Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Name__c</fullName>
        <formula>Stock_Point__r.Service_Engineer_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Engineer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>AMC_Created__c</fullName>
        <label>AMC Created</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AMC_Type__c</fullName>
        <label>AMC Type</label>
        <picklist>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Comprehensive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Bill_No__c</fullName>
        <label>Service Bill No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Type__c</fullName>
        <label>Service Charge Type</label>
        <picklist>
            <controllingField>AMC_Status__c</controllingField>
            <picklistValues>
                <fullName>Carry In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Engineer Assigned</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <formula>Service_Engineer_Assigned__r.Service_Engineer_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Engineer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Name__c</fullName>
        <label>Service Engineer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <inlineHelpText>Required Field . Should match Oracle AR Customer Number</inlineHelpText>
        <label>Service Engineer Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Name__c</fullName>
        <label>Service Engineer Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AutoPopulationTest.cls
@isTest
public class AutoPopulationTest{
    static testMethod void AutoPopulationTestMethod(){   
    
        User u = [Select Id from user where profile.name = 'Service Center' and IsActive = true limit 1];
        
        Stock_Point__c StockPt1 = new Stock_Point__c();
        //StockPt1.RecordTypeId = [Select Id from RecordType where Name = 'Service Engineer' And SObjectType = 'Stock_Point__c'].Id;
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
		Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
		Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Engineer');
		StockPt1.RecordTypeId = rtByName.getRecordTypeId();

        StockPt1.Service_Engineer_Name__c = 'TestEngineer1';
        StockPt1.ownerId = u.Id;
        StockPt1.Name = 'PARWEZ ALAM';
        StockPt1.Service_Center_Location_Code__c='051-SC-PATNA';
        StockPt1.Service_Engineer_Id__c = 'P900257';
        Insert StockPt1;
        
        Current_Inventory_Component__c CurrentStock = new Current_Inventory_Component__c();
        CurrentStock.Name = 'Test';
        CurrentStock.Defective_Quantity_in_Hand__c = 5;
        CurrentStock.Usable_Quantity_in_Hand__c = 2;
        CurrentStock.Component_Code__c = '1001';
        CurrentStock.Stock_Point__c= StockPt1.Id;
        Insert CurrentStock;
        
        
        Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        Prod.CurrencyIsoCode = 'INR';
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        Price_Books__c PriceBk0 = new Price_Books__c();
        PriceBk0.Name = 'Standard Price Book';
        PriceBk0.Description__c = 'Standard Price Book';
        PriceBk0.IsActive__c = True;
        Insert PriceBk0;
        
        Price_Book_Entry__c StdPBEntry = new Price_Book_Entry__c();
        StdPBEntry.CurrencyIsoCode = Prod.CurrencyIsoCode;
        StdPBEntry.UnitPrice__c = 1000;
        StdPBEntry.IsActive__c = True;
        StdPBEntry.Product__c = Prod.Id;
        StdPBEntry.Price_book__c = [Select Id from Price_Books__c where Name = 'Standard Price Book' Limit 1].Id;
        Insert StdPBEntry;
        
        //////////1
        Price_Books__c PriceBk1 = new Price_Books__c();
        PriceBk1.Name = 'Comprehensive AMC Rate';
        PriceBk1.Description__c = 'Comprehensive AMC Rate';
        PriceBk1.IsActive__c = True;
        Insert PriceBk1;
        
        Price_Book_Entry__c PBEntry1 = new Price_Book_Entry__c();
        PBEntry1.CurrencyIsoCode = Prod.CurrencyIsoCode;
        PBEntry1.UnitPrice__c = 100;
        PBEntry1.IsActive__c = True;
        PBEntry1.Product__c = Prod.Id;
        PBEntry1.Price_book__c = PriceBk1.Id;
        Insert PBEntry1;
        
        //////////2
        Price_Books__c PriceBk2 = new Price_Books__c();
        PriceBk2.Name = 'Non-Comprehensive AMC Rate';
        PriceBk2.Description__c = 'Non-Comprehensive AMC Rate';
        PriceBk2.IsActive__c = True;
        Insert PriceBk2;
        
        Price_Book_Entry__c PBEntry2 = new Price_Book_Entry__c();
        PBEntry2.CurrencyIsoCode = Prod.CurrencyIsoCode;
        PBEntry2.UnitPrice__c = 100;
        PBEntry2.IsActive__c = True;
        PBEntry2.Product__c = Prod.Id;
        PBEntry2.Price_book__c = PriceBk2.Id;
        Insert PBEntry2;
        
        //////////3
        Price_Books__c PriceBk3 = new Price_Books__c();
        PriceBk3.Name = 'Carry In Service Charges';
        PriceBk3.Description__c = 'Carry In Service Charges';
        PriceBk3.IsActive__c = True;
        Insert PriceBk3;
        
        Price_Book_Entry__c PBEntry3 = new Price_Book_Entry__c();
        PBEntry3.CurrencyIsoCode = Prod.CurrencyIsoCode;
        PBEntry3.UnitPrice__c = 100;
        PBEntry3.IsActive__c = True;
        PBEntry3.Product__c = Prod.Id;
        PBEntry3.Price_book__C = PriceBk3.Id;
        Insert PBEntry3;
        
        //////////4
        Price_Books__c PriceBk4 = new Price_Books__c();
        PriceBk4.Name = 'On Site Service Charges';
        PriceBk4.Description__c = 'On Site Service Charges';
        PriceBk4.IsActive__c = True;
        Insert PriceBk4;
        
        Price_Book_Entry__c PBEntry4 = new Price_Book_Entry__c();
        PBEntry4.CurrencyIsoCode = Prod.CurrencyIsoCode;
        PBEntry4.UnitPrice__c = 100;
        PBEntry4.IsActive__c = True;
        PBEntry4.Product__c = Prod.Id;
        PBEntry4.Price_book__C = PriceBk4.Id;
        Insert PBEntry4;
        
        //////////5
        Price_Books__c PriceBk5 = new Price_Books__c();
        PriceBk5.Name = 'Visit Service Charges';
        PriceBk5.Description__c = 'Visit Service Charges';
        PriceBk5.IsActive__c = True;
        Insert PriceBk5;
        
        Price_Book_Entry__c PBEntry5 = new Price_Book_Entry__c();
        PBEntry5.CurrencyIsoCode = Prod.CurrencyIsoCode;
        PBEntry5.UnitPrice__c = 100;
        PBEntry5.IsActive__c = True;
        PBEntry5.Product__c = Prod.Id;
        PBEntry5.Price_book__C = PriceBk5.Id;
        Insert PBEntry5;
        
        /////////////////CASE
        
        Service_Request__c  Cas = new Service_Request__c ();
        //Cas.Service_Engineer_Assigned__c = StockPt1.Id;
        Cas.Service_Bill_No__c = 'ww';
        Cas.Products__c = Prod.Id;
        Cas.AMC_Created__c = 'Yes';
        Cas.AMC_Type__c = 'Comprehensive';
        Cas.Service_Charge_Type__c = 'Carry In';
        Cas.Origin__c = 'Web';
        Cas.Product_Serial_No__c = '0101';
        Cas.ownerId = u.Id;
        Cas.Warranty_Status__c = 'No';
        Cas.AMC_Status__c = 'No';
        Cas.Total_Defective_Quantity_Returned__c = 1;
        Cas.Total_Quantity_Issued__c = 1;
        cas.Product_Code__c = '1001';
        Insert Cas;
        
        Cas.AMC_Type__c = 'Non-Comprehensive'; 
        Cas.Service_Charge_Type__c = 'On Site';
        Update Cas;
        
        Cas.Service_Charge_Type__c = 'Visit';
        Update Cas;
        
    }
}