src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Estimated_Value_of_Service_Request__c</fullName>
        <label>Estimated Value of Service Request</label>
        <picklist>
            <controllingField>Type_of_Replacement__c</controllingField>
            <picklistValues>
                <fullName>Upto INR 50,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Above INR 50,000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FSR_No__c</fullName>
        <externalId>true</externalId>
        <label>FSR No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FSR_Trig__c</fullName>
        <externalId>true</externalId>
        <label>FSR Trig</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Replacement__c</fullName>
        <label>Type of Replacement</label>
        <picklist>
            <controllingField>Type_of_Service_Request__c</controllingField>
            <picklistValues>
                <fullName>Component Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Replacement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Service_Request__c</fullName>
        <label>Type of Service Request</label>
        <picklist>
            <controllingField>Warranty_Status__c</controllingField>
            <picklistValues>
                <fullName>Sale of Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Value_of_Service_Request__c</fullName>
        <label>Estimated Value of Service Request</label>
        <picklist>
            <controllingField>Type_of_Replacement__c</controllingField>
            <picklistValues>
                <fullName>Upto INR 50,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Above INR 50,000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FSR_No__c</fullName>
        <externalId>true</externalId>
        <label>FSR No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FSR_Trig__c</fullName>
        <externalId>true</externalId>
        <label>FSR Trig</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON MAINS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAINS MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BLOWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BROKEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWITCH FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM ON BUT NO OUTPUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM DEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS LOW BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER LOAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS SHORT CIRCUIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING CONTINUSELY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT CHARGING BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY OVERHEATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY DRY RUN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONNECTOR BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSIT DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSFORMER BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARD BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANGEOVER PROBLEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAN NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOOSE CONNECTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOCKET DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAIN LEAD FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED DISPLAY NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER TEMPERATURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY LOW BACKUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM GENERATES HUMMING SOUND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Replacement__c</fullName>
        <label>Type of Replacement</label>
        <picklist>
            <controllingField>Type_of_Service_Request__c</controllingField>
            <picklistValues>
                <fullName>Component Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Replacement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Service_Request__c</fullName>
        <label>Type of Service Request</label>
        <picklist>
            <controllingField>Warranty_Status__c</controllingField>
            <picklistValues>
                <fullName>Sale of Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/sendSMSclsTWOTest.cls
/*
        -----------------------------------------
        CREATED BY      : Lister Technologies.
        CREATED ON      : 27/01/2010
        CREATED PURPOSE : Test class for the trigger trgSendSMS and class sendSMScls
        -----------------------------------------
                                                     */
                                                     
@isTest
private class sendSMSclsTWOTest
{
 
  
  public static testMethod void testing()
  {
     try
     {
          //Creating an account
          
          Account testAcc=new Account();
          testAcc.Name='test';
          testAcc.BillingStreet='11';
          testAcc.BillingCity='22';
          testAcc.BillingState='33';
          testAcc.BillingPostalCode='44';
          testAcc.BillingCountry='55';
          testAcc.Phone='09884504501';
          testAcc.ShippingStreet='11';
          testAcc.ShippingCity='22';
          testAcc.ShippingState='33';
          testAcc.ShippingPostalCode='44';
          testAcc.ShippingCountry='55';
         
          insert testAcc;
          
          //creating a contact
          Contact testContact=new Contact();
          testContact.FirstName='testFirst';
          testContact.LastName='testLast'; 
          testContact.AccountId=testAcc.Id;
          testContact.mobilePhone='09884504501';
          testContact.Email='jayashree.ramamoorthy@listertechnologies.com';
          
          insert testContact;
           
          //creating a case
          Service_Request__c testCase=new Service_Request__c();
          testCase.ownerId='00520000000qStb';
          testCase.account__c=testAcc.Id;
          testCase.Status__c='Assigned';
          testCase.origin__c='Email';
          testCase.Contact__c=testContact.ID;
          testCase.Description__c='sending test sms';
          testCase.FSR_No__c='a';
          testCase.FSR_Trig__c=1111;
          
          insert testCase;
          
          
          sendSMScls.sendSMS(new List<String>{'09884504501'},new List<String>{'hello'},new List<ID>{testCase.Id},new List<String>{'14111111111'},FALSE);
          
          testCase.Type_of_Service_Request__c='Warranty';
          testCase.Status__c='Closed';
          testCase.Reason__c='SYSTEM DEAD';
          testCase.Type_of_Replacement__c='Component Replacement';
          testCase.Warranty_Status__c='Yes';
          testCase.Product_Serial_No__c='12';
          testCase.Estimated_Value_of_Service_Request__c='Upto INR 50,000';
          
          
          
          update testCase;
      }//try
      catch(Exception e)
      {
        System.debug('caught the exception'+e);
      }
     
  }//test method

}//test class