src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <formula>Select_Component__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Component Code 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Status__c</fullName>
        <label>Component Status</label>
        <picklist>
            <picklistValues>
                <fullName>Usable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Defective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_Returned__c</fullName>
        <label>Defective Quantity Returned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRN_No_Trig__c</fullName>
        <label>MRN No Trig</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_from_Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Received from Stock Point</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table</relationshipLabel>
        <relationshipName>Components_Movement_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used in Product Sale</description>
        <label>Service Engineer Assigned</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table (Service Engineer Assigned)</relationshipLabel>
        <relationshipName>Components_Movement_Table2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Service_Request__c</referenceTo>
        <relationshipLabel>Components Movement Table</relationshipLabel>
        <relationshipName>Components_Movement_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_Point_to_be_Reconciled__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Stock Point to be Reconciled</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table (Stock Point to be Reconciled)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Entry__c</fullName>
        <label>Type of Entry</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deduct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Receipt__c</fullName>
        <label>Type of Receipt</label>
        <picklist>
            <picklistValues>
                <fullName>Returned by Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Returned by Service Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <recordTypes>
        <fullName>Reconciliation</fullName>
        <active>true</active>
        <description>Reconciliation of Stocks</description>
        <label>Reconciliation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_in_Hand__c</fullName>
        <label>Defective Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <recordTypes>
        <fullName>Components</fullName>
        <active>true</active>
        <description>List of all Components</description>
        <label>Components</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Service_Center_Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <recordTypes>
        <fullName>ServiceEngineer</fullName>
        <active>true</active>
        <label>Service Engineer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ComponentMovementTest1.cls
@isTest
public class ComponentMovementTest1{
    static testMethod void ComponentMovementTestMethod1(){ 
        try{
        Product__c Prod = new Product__c();
        Prod.name = 'Testt';
        Prod.Product_Code__c = '10011';
    
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        Product__c Prod1 = new Product__c();
        Prod1.name = 'Testt1';
        Prod1.Product_Code__c = '10022';
       
        Prod1.Is_Active__c = True;
        Prod1.UoM__c = 'Set';
        Insert Prod1;
        
        Price_Books__C PriceBk = new Price_Books__C();
        PriceBk.Name = 'Carry In Service Charges';
        PriceBk.Description__c = 'Carry In Service Charges';
        PriceBk.IsActive__c = True;
        Insert PriceBk;
        
        Price_Book_Entry__c StdPBEntry = new Price_Book_Entry__c();
        
        StdPBEntry.UnitPrice__c = 1000;
        StdPBEntry.IsActive__c = True;
        StdPBEntry.Product__c = Prod.Id;
        StdPBEntry.Price_Book__C = [Select Id from Price_Books__C where Name = 'Standard Price Book' Limit 1].Id;
        Insert StdPBEntry;
        
        Price_Book_Entry__c PBEntry = new Price_Book_Entry__c();
        
        PBEntry.UnitPrice__c = 100;
        PBEntry.IsActive__c = True;
        PBEntry.Product__c = Prod.Id;
        PBEntry.Price_Book__C = PriceBk.Id;
        Insert PBEntry;
        
        User[] Usr = [Select Id from User where Profile.name='Service Center' and IsActive=True Limit 2];
        
        User u = Usr[0];
            
        User u2 = Usr[0];
        
        //for(Stock_Point__c StP: [Select Id from Stock_Point__c where OwnerId = :u.Id or OwnerId = :u2.Id])            
          //  Delete StP;
            
        /*Current_Inventory_Component__c InTransitInventory = new Current_Inventory_Component__c();
        InTransitInventory.Stock_Point__c = [Select Id from Stock_point__c where Service_Center_Description__c = 'In Transit' Limit 1].Id;
        InTransitInventory.Component_Code__c = Prod.ProductCode;
        InTransitInventory.Name = Prod.Name;
        InTransitInventory.Usable_Quantity_in_hand__c = 500;
        InTransitInventory.Defective_Quantity_in_hand__c = 500;
        Insert InTransitInventory;*/
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
		Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
		Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Center');
		Id screctypeid = rtByName.getRecordTypeId();
		
		Schema.RecordTypeInfo rtByName1 =  rtMapByName.get('Service Engineer');
		Id serectypeid = rtByName1.getRecordTypeId();
		
        Stock_Point__c StockPt1 = new Stock_Point__c();
        StockPt1.RecordTypeId = screctypeid;  //[Select Id from RecordType where Name = 'Service Center' And SObjectType = 'Stock_Point__c'].Id;
        StockPt1.Service_Center_Description__c = 'TestCenter1';
        StockPt1.Service_Center_Address__c = 'Address1';
        StockPt1.OwnerId = u2.Id;
        StockPt1.Service_Center_Location_Code__c = '033-';
        Insert StockPt1;
        
        Current_Inventory_Component__c TempInventory = new Current_Inventory_Component__c();
        TempInventory.Stock_Point__c = StockPt1.Id;
        TempInventory.Component_Code__c = Prod.Product_Code__c;
        TempInventory.Name = Prod.Name;
        TempInventory.Usable_Quantity_in_hand__c = 500;
        TempInventory.Defective_Quantity_in_hand__c = 500;
        Insert TempInventory;
        
        System.runAs(u)
        {
            Stock_Point__c StockPt = new Stock_Point__c();
            StockPt.RecordTypeId = screctypeid;  //[Select Id from RecordType where Name = 'Service Center' And SObjectType = 'Stock_Point__c'].Id;
            StockPt.Service_Center_Description__c = 'TestCenter2';
            StockPt.Service_Center_Address__c = 'Address2';
            StockPt.Service_Center_Location_Code__c = '044-';
            Insert StockPt;
            
            Current_Inventory_Component__c TempInventory2 = new Current_Inventory_Component__c();
            TempInventory2.Stock_Point__c = StockPt.Id;
            TempInventory2.Component_Code__c = Prod1.Product_Code__c;
            TempInventory2.Name = Prod1.Name;
            TempInventory2.Usable_Quantity_in_hand__c = 500;
            TempInventory2.Defective_Quantity_in_hand__c = 500;
            Insert TempInventory2;
            
            Stock_Point__c ServiceEngineer = new Stock_Point__c();
            ServiceEngineer.RecordTypeId = serectypeid;  //[Select Id from RecordType where Name = 'Service Engineer' And SObjectType = 'Stock_Point__c'].Id;
            ServiceEngineer.Service_Center_Description__c = 'TestEngineer';
            ServiceEngineer.Service_Center_Address__c = 'Address22';
            ServiceEngineer.Service_Center_Location_Code__c = '022';
            Insert ServiceEngineer;
            
            Current_Inventory_Component__c TempInventory3 = new Current_Inventory_Component__c();
            TempInventory3.Stock_Point__c = ServiceEngineer.Id;
            TempInventory3.Component_Code__c = Prod.Product_Code__c;
            TempInventory3.Name = Prod.Name;
            TempInventory3.Usable_Quantity_in_hand__c = 500;
            TempInventory3.Defective_Quantity_in_hand__c = 500;
            Insert TempInventory3;
            
            ////////////////////////INWARD MOVEMENT///////////////////////////////////////
            
            Schema.DescribeSObjectResult d2 = Schema.SObjectType.Component_Movement_Table__c;
			Map<String,Schema.RecordTypeInfo> rtMapByName2 = d2.getRecordTypeInfosByName();
			Schema.RecordTypeInfo rtByName2 =  rtMapByName2.get('Inward Movement');
			Id imrectypeid = rtByName2.getRecordTypeId();
			
			Schema.RecordTypeInfo rtByName3 =  rtMapByName2.get('Reconciliation');
			Id recrectypeid = rtByName3.getRecordTypeId();
			
		
            Id InwardMovementRecordTypeId = imrectypeid;  //[Select Id from RecordType where Name = 'Inward Movement' and SObjectType = 'Component_Movement_Table__c' Limit 1].Id;
            //Scenario 1
            Component_Movement_Table__c CompMove1 = new Component_Movement_Table__c();
            CompMove1.RecordTypeId = InwardMovementRecordTypeId;
            CompMove1.Type_of_receipt__c = 'Stock Transfer';
            CompMove1.Component_Status__c = 'Usable';
            CompMove1.Select_Component__c = Prod.Id;
            CompMove1.Quantity__c = 10;
            CompMove1.OwnerID=u.id;
            CompMove1.Received_from_Stock_Point__c = StockPt1.Id;
            Insert CompMove1;
            
            //Scenario 2
            Component_Movement_Table__c CompMove2 = new Component_Movement_Table__c();
            CompMove2.RecordTypeId = InwardMovementRecordTypeId;
            CompMove2.Type_of_receipt__c = 'Returned by Customer';
            CompMove2.Component_Status__c = 'Usable';
            CompMove2.Select_Component__c = Prod.Id;
            CompMove2.Quantity__c = 10;
            CompMove2.MRN_No_Trig__c=1;
            CompMove2.OwnerID=u.id;
            CompMove2.Defective_Quantity_Returned__c=1;
            //CompMove2.Received_from_Stock_Point__c = StockPt1.Id;
            Insert CompMove2;
            
            //Scenario 3
            Component_Movement_Table__c CompMove3 = new Component_Movement_Table__c();
            CompMove3.RecordTypeId = InwardMovementRecordTypeId;
            CompMove3.Type_of_receipt__c = 'Stock Returned by Service Engineer';
            CompMove3.Component_Status__c = 'Usable';
            CompMove3.Select_Component__c = Prod.Id;
            CompMove3.Quantity__c = 10;
            CompMove3.Defective_Quantity_Returned__c=1;
            CompMove3.MRN_No_Trig__c=1;
            CompMove3.OwnerID=u.id;
            CompMove3.Received_from_Stock_Point__c = ServiceEngineer.Id;
            Insert CompMove3;
            
            ///////////////////////////RECONCILIATION//////////////////////////////////
            
            Id ReconciliationRecordTypeId = recrectypeid;  //[Select Id from RecordType where Name = 'Reconciliation' and SObjectType = 'Component_Movement_Table__c' Limit 1].Id;
            //Scenario 6
            Component_Movement_Table__c CompMove6 = new Component_Movement_Table__c();
            CompMove6.RecordTypeId = ReconciliationRecordTypeId;
            CompMove6.Type_of_Entry__c = 'Add';
            CompMove6.Component_Status__c = 'Usable';
            CompMove6.Select_Component__c = Prod.Id;
            CompMove6.Quantity__c = 10;
            CompMove6.OwnerID=u.id;
            CompMove6.Stock_point_to_be_reconciled__c = StockPt1.Id;
            Insert CompMove6;
            
            //Scenario 6.1
            Component_Movement_Table__c CompMove61 = new Component_Movement_Table__c();
            CompMove61.RecordTypeId = ReconciliationRecordTypeId;
            CompMove61.Type_of_Entry__c = 'Add';
            CompMove61.Component_Status__c = 'Usable';
            CompMove61.Select_Component__c = Prod1.Id;
            CompMove61.Quantity__c = 10;
            CompMove61.OwnerID=u.id;
            CompMove61.Stock_point_to_be_reconciled__c = StockPt1.Id;
            Insert CompMove61;
            
            //Scenario 7
            Component_Movement_Table__c CompMove7 = new Component_Movement_Table__c();
            CompMove7.RecordTypeId = ReconciliationRecordTypeId;
            CompMove7.Type_of_Entry__c = 'Deduct';
            CompMove7.Component_Status__c = 'Usable';
            CompMove7.Select_Component__c = Prod.Id;
            CompMove7.Quantity__c = 10;
            CompMove7.Stock_point_to_be_reconciled__c = StockPt1.Id;
            Insert CompMove7;
            
            ///////////////////////////USED IN SERVICE REQUEST//////////////////////////////////
            
            Service_Request__c Cas = new Service_Request__c();
            Cas.Origin__c = 'Email';
            Cas.Product_Serial_No__c = '0101';
            Cas.Service_Engineer_Assigned__c = ServiceEngineer.Id;
            Insert Cas;
            
            /*Id ServiceRequestRecordTypeId = [Select Id from RecordType where Name = 'Components Used in Service Request' and SObjectType = 'Component_Movement_Table__c' Limit 1].Id;
            //Scenario 9
            Component_Movement_Table__c CompMove9 = new Component_Movement_Table__c();
            CompMove9.RecordTypeId = ServiceRequestRecordTypeId;
            CompMove9.Service_Request__c = Cas.Id;
            CompMove9.Select_Component__c = Prod.Id;
            CompMove9.Quantity__c = 10;
            CompMove9.Defective_Quantity_Returned__c = 5;
            
            Insert CompMove9;
            
            //Scenario 9
            Component_Movement_Table__c CompMove91 = new Component_Movement_Table__c();
            CompMove91.RecordTypeId = ServiceRequestRecordTypeId;
            CompMove91.Service_Request__c = Cas.Id;
            CompMove91.Select_Component__c = Prod.Id;
            CompMove91.Quantity__c = 10;
            CompMove91.Defective_Quantity_Returned__c = 5;
            
            Insert CompMove91;
            
            //CompMove91.Defective_Quantity_Returned__c = 6;
            Update CompMove91;*/
            
            ///////////////////////////CANCELLATIONS//////////////////////////////////
            
            CompMove1.Cancelled__c = True;
            Update CompMove1;
            
            CompMove2.Cancelled__c = True;
            //Update CompMove2;
            
            CompMove3.Cancelled__c = True;
            //Update CompMove3;
            
            CompMove6.Cancelled__c = True;
            //Update CompMove6;
            
            CompMove7.Cancelled__c = True;
            //Update CompMove7;
          
          
        
        }            
         }catch(Exception e){}       
        
    
    }
}