src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used in Product Sale</description>
        <label>Service Engineer Assigned</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table (Service Engineer Assigned)</relationshipLabel>
        <relationshipName>Components_Movement_Table2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserAddress__c</fullName>
        <label>UserAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch_State__c</fullName>
        <label>Branch State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/testUpdateUserAddress.cls
@isTest
public class testUpdateUserAddress
{
  static testmethod void testUpdateAddressMthd()
  {
   //Id UserId = '00590000000c9vE' ;
   User objUser = [SELECT LastName, City, Branch_State__c, Division, FirstName, Name FROM User where id =: '00590000000c9vE'];
   
   system.assert(objUser != null);
   //Component_Movement_Table__c obj = [select id,UserAddress__c from Component_Movement_Table__c  where id =:'a07O0000005FB6C'];
   //obj.id = 'a07O0000005FB6C';
   //system.Assert(obj != null);
   
   Component_Movement_Table__c obj = new Component_Movement_Table__c();
   obj.UserAddress__c  = 'Gurgaon ,Haryana' ;
   obj.CurrencyIsoCode = 'INR - Indian Rupee'; 
   obj.Service_Engineer_Assigned__c = 'a0bO0000000oZVU';
   obj.Quantity__c = 1;
   obj.Select_Component__c = 'a04O0000004na7Z';
   try
   {
     insert obj;
   }
   catch(System.DMLException e)
   {
     //System.assert(e.getMessage().contains('Record already exist '));
   }
   
  }

}