src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dispatched_Through__c</fullName>
        <label>Dispatched Through</label>
        <picklist>
            <picklistValues>
                <fullName>By Hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>By Courier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Invoice_No__c</fullName>
        <label>Document / Invoice No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generate_Invoice_Bill_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Invoice &amp; Bill No.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_No_Trig_No__c</fullName>
        <label>Invoice_No_Trig_No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Road_Permit__c</fullName>
        <label>Road Permit</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_Invoice_No.cls
@isTest
Public Class test_Invoice_No{
    public static testmethod void Invoice_no(){
            RecordType RecordTypeID;
    Invoice_no inv = new Invoice_no();
    String strMonth = String.ValueOf(DateTime.Now().month());
    Integer intMonth=4;
    
        User testSM1 = new User();
        testSM1.FirstName = 'test';
        testSM1.LastName = 'SM1';
        testSM1.isActive = true;
        testSM1.Email = 'testSM1@test.com.testuser';
        testSM1.Username = 'testSM1@test.com.testuser';
        testSM1.Alias = 'testSM1';
        testSM1.CommunityNickname = 'testSM1';
        testSM1.TimeZoneSidKey = 'GMT';
        testSM1.LocaleSidKey = 'en_US';
        testSM1.EmailEncodingKey = 'UTF-8';
        testSM1.LanguageLocaleKey = 'en_US';
        testSM1.ProfileId = [Select ID From Profile Where Name =: 'System Administrator' Limit 1][0].Id;
        insert testSM1;   
    
    
        Stock_Point__c StockPt = new Stock_Point__c();
        StockPt.Name = 'ABC';
        StockPt.Service_Center_Location_Code__c = '000hi5858';
        StockPt.Region__c = 'CENTRAL';
        String recid = Schema.SObjectType.Stock_Point__c.getRecordTypeInfosByName().get('Service Center').getRecordTypeId();
        StockPt.RecordTypeID = recid; //[Select id from RecordType where Sobjecttype = 'Stock_Point__c' and name = 'Service Center'].Id;
        StockPt.ownerID = testSM1.id;
        System.debug('++++++RecordTypeID +++++++'+StockPt.RecordTypeID);
        insert StockPt;
    
        Product__c prod = new Product__c();
        prod.Name = 'prod';
        prod.Product_Code__c = 'ABC';
        prod.CurrencyIsoCode = 'INR';
        prod.Is_Active__c = True ;
        insert prod;
    
       system.debug('=====testSM1======='+testSM1);
        Component_Movement_Table__c  cmvt = new Component_Movement_Table__c();
        cmvt.Dispatched_Through__c = 'By Hand';
        cmvt.Date__c = System.today();
        cmvt.Road_Permit__c = 'No';
        cmvt.Select_Component__c = prod.id;
        cmvt.Invoice_No_Trig_No__c = 123;
        cmvt.Document_Invoice_No__c = '1315675000003';
        cmvt.ownerID = testSM1.id;
        system.debug('=====cmvt.ownerID======='+cmvt.ownerID);
        
    
    Schema.DescribeSObjectResult d = Schema.SObjectType.Component_Movement_Table__c;
    Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
    Schema.RecordTypeInfo rtByName =  rtMapByName.get('Product Sale');
    cmvt.RecordTypeID = rtByName.getRecordTypeId();
    insert cmvt;
    system.debug('=====cmvt.ownerID 222======='+cmvt.ownerID);
    cmvt.Generate_Invoice_Bill_No__c = true;
    update cmvt;
    system.debug('=====cmvt.ownerID 333======='+cmvt.ownerID);
    
    
    Component_Movement_Table__c  cmt = new Component_Movement_Table__c();
        cmt.Dispatched_Through__c = 'By Hand';
        cmt.Date__c = System.today();
        cmt.Road_Permit__c = 'No';
        cmt.Select_Component__c = prod.id;
        cmt.Invoice_No_Trig_No__c = 123;
        cmt.Document_Invoice_No__c = '1315675000003';
        cmt.ownerID = testSM1.id;
        system.debug('=====cmt.ownerID======='+cmt.ownerID);
        
    
    
    cmt.RecordTypeID = rtByName.getRecordTypeId();
    insert cmt;
    system.debug('=====cmt.ownerID 222======='+cmt.ownerID);
    cmt.Generate_Invoice_Bill_No__c = true;
    update cmt;
    
    
    }  
}