src/objects/Component_Movement_line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Select_Component__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Select_Component_Code__c</fullName>
        <formula>Select_Component__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Select Component Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Component Movement line Items</relationshipLabel>
        <relationshipName>Component_Movement_line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <formula>Component_Movement_Table__r.Service_Engineer_Assigned__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Engineer Assigned</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Transfer_Price_Unit__c</fullName>
        <label>Stock Transfer Price / Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Percent__c</fullName>
        <label>VAT Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Component Movement line Item</label>
    <nameField>
        <displayFormat>TLID-{0000000}</displayFormat>
        <label>Component Movement line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Movement line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_in_Hand__c</fullName>
        <label>Defective Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>COMPONENT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>This will contain the names of the different states, branch email ids &amp; the details of managers &amp; accountants</description>
    <label>Branch Details</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch_Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>State__c</fullName>
        <formula>$User.State</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VAT1__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPONENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ANDHRA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANDIGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHATTISGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GUJARAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HARYANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIMACHAL PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J&amp;K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JHARKHAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KARNATAKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KERALA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MADHYA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAHARASHTRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORISSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUNJAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAJASTHAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAMIL NADU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTTAR PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTTARAKHAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST BENGAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT_Percentage__c</fullName>
        <label>VAT Percentage</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>VAT</label>
    <nameField>
        <label>VAT Record  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ComponentMovementLineItemTriggerUtil.cls
public class ComponentMovementLineItemTriggerUtil {
    
    public static void populateSalesPrice(List<Component_Movement_line_Item__c> cmtliList) {
        
        Set<Id> setProductIds = new Set<Id>();
        for(Component_Movement_line_Item__c cmtli :cmtliList) {
            setProductIds.add(cmtli.Select_Component__c);
        }
        
        List<Price_Book_Entry__c> pbeList = [select Product__c, Price_Book__r.Name, UnitPrice__c 
                         from Price_Book_Entry__c where Product__c = :setProductIds
                         and Price_Book__r.Name = 'Sale Price'];
        
        Map<Id, Decimal> mapProductPrice = new Map<Id, Decimal>();
        
        for(Price_Book_Entry__c pbe :pbeList) {
            mapProductPrice.put(pbe.Product__c, pbe.UnitPrice__c);
        }
        
        for(Component_Movement_line_Item__c cmtli :cmtliList) {
            if(mapProductPrice != null && mapProductPrice.containsKey(cmtli.Select_Component__c)) {
                cmtli.Stock_Transfer_Price_Unit__c = mapProductPrice.get(cmtli.Select_Component__c);
            }
        }
    }
    
    public static void deductQuantityFromStockPoint(List<Component_Movement_line_Item__c> cmtliList) {
        
        Set<String> productCode = new Set<String>();
        Map<Id, Map<String, Decimal>> mapStkPointProduct = new Map<Id, Map<String, Decimal>>();
        
        for(Component_Movement_line_Item__c cmtli :cmtliList) {
            Id stkPtId = cmtli.Service_Engineer_Assigned__c;
            productCode.add(cmtli.Select_Component_Code__c);
            Decimal quantity = 0;
            Map<String, Decimal> mapProductQuantity = new Map<String, Decimal>();
            
            if(mapStkPointProduct != null && mapStkPointProduct.containsKey(stkPtId)) {
                mapProductQuantity = mapStkPointProduct.get(stkPtId);
                if(mapProductQuantity != null && mapProductQuantity.containsKey(cmtli.Select_Component_Code__c)) {
                    quantity += mapProductQuantity.get(cmtli.Select_Component_Code__c);
                }
            }
            quantity += cmtli.Quantity__c;
            mapProductQuantity.put(cmtli.Select_Component_Code__c, quantity);
            mapStkPointProduct.put(stkPtId, mapProductQuantity);
        }
        System.debug('--productCode--'+ productCode);
        System.debug('--mapStkPointProduct--'+ mapStkPointProduct);
        List<Current_Inventory_Component__c> stockList = [Select Component_Code__c, Usable_Quantity_in_Hand__c, 
                        Defective_Quantity_in_Hand__c, Stock_Point__c 
                        from Current_Inventory_Component__c where Stock_Point__c in :mapStkPointProduct.keySet() 
                        and Component_Code__c in :productCode];
        
        if(stockList == null || stockList.size() == 0)
            trigger.new[0].addError('All component(s) that you are requesting is(are) not available in the Stock Point to complete the transaction');
        
        Map<Id, Map<String, Current_Inventory_Component__c>> mapStkPtProdStock = new Map<Id, Map<String, Current_Inventory_Component__c>>();
        for(Current_Inventory_Component__c stk :stockList) {
            Id stkPtId = stk.Stock_Point__c;
            Current_Inventory_Component__c stkRecord = new Current_Inventory_Component__c();
            Map<String, Current_Inventory_Component__c> mapProductStock = new Map<String, Current_Inventory_Component__c>();
            
            if(mapStkPtProdStock != null && mapStkPtProdStock.containsKey(stkPtId)) {
                mapProductStock = mapStkPtProdStock.get(stkPtId);
                if(mapProductStock != null && mapProductStock.containsKey(stk.Component_Code__c)) {
                    stkRecord = mapProductStock.get(stk.Component_Code__c);
                }
            }
            stkRecord = stk;
            mapProductStock.put(stk.Component_Code__c, stkRecord);
            mapStkPtProdStock.put(stkPtId, mapProductStock);
        }
                            
        for(Id stkid :mapStkPointProduct.keySet()) {
            Map<String, Decimal> mapProdQtyTemp = new Map<String, Decimal>();
            mapProdQtyTemp = mapStkPointProduct.get(stkid);
            for(String prod :mapProdQtyTemp.keySet()) {
                if(mapStkPtProdStock != null && mapStkPtProdStock.containsKey(stkid)) {
                    Map<String, Current_Inventory_Component__c> mapProdStkTemp = new Map<String, Current_Inventory_Component__c>();
                    mapProdStkTemp = mapStkPtProdStock.get(stkid);
                    if(mapProdStkTemp != null && mapProdStkTemp.containsKey(prod)) {
                        Current_Inventory_Component__c stk = mapProdStkTemp.get(prod);
                        Decimal qty = mapProdQtyTemp.get(prod);
                        if(stk.Usable_Quantity_in_Hand__c != null && stk.Usable_Quantity_in_Hand__c >= qty) {
                            stk.Usable_Quantity_in_Hand__c = stk.Usable_Quantity_in_Hand__c - qty;
                        } else {
                            trigger.new[0].addError('Insuffecient Usable quantity  for ' + prod + ' in the Stock Point to complete the transaction');
                        }
                    } else {
                        trigger.new[0].addError('The component '+ prod +' is not available in the Stock Point to complete the transaction');
                    }
                } else {
                    trigger.new[0].addError('Component is not available in stock point.');
                }
            }
        }
        
        try {
            if(stockList != null && stockList.size() > 0)
                update stockList;
        } catch(Exception e) {
            trigger.new[0].addError(e.getMessage());
        }
    }
    
    public static void populateVatOnLineItem(List<Component_Movement_line_Item__c> cmtliList) {
        User loggedInUser = [select State from User where id = :UserInfo.getUserId()];
    
        Set<String> setCategory = new Set<String>();
        for(Component_Movement_line_Item__c cmtli :cmtliList) {
            setCategory.add(cmtli.Product_Category__c);
        }
        
        List<VAT1__c> vatList = [select VAT_Percentage__c, Product_Category__c from VAT1__c 
                        where State__c = :loggedInUser.State and Product_Category__c in :setCategory];
        
        Map<String, Decimal> mapCategoryVat = new Map<String, Decimal>();
        
        for(VAT1__c vat :vatList) {
            mapCategoryVat.put(vat.Product_Category__c, vat.VAT_Percentage__c);
        }
        
        for(Component_Movement_line_Item__c cmtli :cmtliList) {
            if(mapCategoryVat != null && mapCategoryVat.containsKey(cmtli.Product_Category__c)) {
                cmtli.VAT_Percent__c = mapCategoryVat.get(cmtli.Product_Category__c);
            }
        }
    }
}