src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Code__c</fullName>
        <formula>Select_Component__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Component Code 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Status__c</fullName>
        <label>Component Status</label>
        <picklist>
            <picklistValues>
                <fullName>Usable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Defective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code_1__c</fullName>
        <label>Product Code 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code_2__c</fullName>
        <label>Product Code 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code_3__c</fullName>
        <label>Product Code 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code_4__c</fullName>
        <label>Product Code 4</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_2__c</fullName>
        <label>Quantity 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_3__c</fullName>
        <label>Quantity 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_4__c</fullName>
        <label>Quantity 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_from_Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Received from Stock Point</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table</relationshipLabel>
        <relationshipName>Components_Movement_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 2</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 2)</relationshipLabel>
        <relationshipName>Components_Movement_Table2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 3</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 3)</relationshipLabel>
        <relationshipName>Components_Movement_Table3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 4</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 4)</relationshipLabel>
        <relationshipName>Components_Movement_Table4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_Point_Type__c</fullName>
        <label>Stock Point Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Receipt__c</fullName>
        <label>Type of Receipt</label>
        <picklist>
            <picklistValues>
                <fullName>Returned by Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Returned by Service Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Service_Center_Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_insertProductNameonCMT.cls
@isTest
public class Test_insertProductNameonCMT{
    public static testMethod void getCodeCoverage(){
        
        Schema.DescribeSObjectResult c = Schema.SObjectType.Component_Movement_Table__c;
        Map<String,Schema.RecordTypeInfo> cmtrtMap = c.getRecordTypeInfosByName();
        Schema.RecordTypeInfo cmtrtByName ;       
       
        Product__c Prod = new Product__c();
        Prod.Name = 'Test Product';
        Prod.Product_Code__c= '1234';
        Prod.Is_Active__c = true;
        Prod.UoM__c = 'Kg';
        insert Prod ;
        
        Product__c Prod1 = new Product__c();
        Prod1.name = 'Test1';
        Prod1.Product_Code__c = '10012';
        Prod1.Is_Active__c = True;
        Prod1.UoM__c = 'Set';
        Insert Prod1;   
        
        Product__c Prod2 = new Product__c();
        Prod2.Name = 'Test Product1';
        Prod2.Product_Code__c= '12414';
        Prod2.Is_Active__c = true;
        Prod2.UoM__c = 'Kg';
        insert Prod2 ;  
        
        Product__c Prod3 = new Product__c();
        Prod3.Name = 'Test Product2';
        Prod3.Product_Code__c= '12400';
        Prod3.Is_Active__c = true;
        Prod3.UoM__c = 'Kg';
        insert Prod3 ;   
        
        User u = new User(
             Alias =  'alia', 
             Email = 'test@sk.com',
             EmailEncodingKey = 'UTF-8', 
             LanguageLocaleKey = 'en_US', 
             LocalesIdKey = 'en_US', 
             TimeZonesIdKey = 'America/Los_Angeles',
             Username = 'test@sk.com',
             LastName = 'lname',
             CommunityNickname = 'cname',
             ProfileId = [select id, Name from Profile where Name = 'Service Center'].id
         );       
        
        insert u;
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
        Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Center');
        Id stockId = rtByName.getRecordTypeId();

        Stock_Point__c StockPt1 = new Stock_Point__c();
        StockPt1.RecordTypeId = stockId ;
        StockPt1.Service_Center_Description__c = 'TestCenter1';
        StockPt1.Service_Center_Address__c = 'Address1';
        StockPt1.OwnerId = u.Id;
        StockPt1.Service_Center_Location_Code__c = '033-';
        Insert StockPt1;
        
        Stock_Point__c StockPt2 = new Stock_Point__c();
        StockPt2.RecordTypeId = stockId ;
        StockPt2.Service_Center_Description__c = 'TestCenter2';
        StockPt2.Service_Center_Address__c = 'Address1';
        StockPt2.OwnerId = u.Id;
        StockPt2.Service_Center_Location_Code__c = '033-';
        Insert StockPt2;
        
        
        Current_Inventory_Component__c  cic = new Current_Inventory_Component__c ();
        cic.Component_code__c = '12400';
        cic.Name = 'test';
        cic.Usable_Quantity_in_Hand__c = 200;
        cic.Stock_Point__c = StockPt1.id;
        insert cic;
        
        
        Current_Inventory_Component__c  cic1 = new Current_Inventory_Component__c ();
        cic1.Component_code__c = '12345';
        cic1.Name = 'test';
        cic1.Usable_Quantity_in_Hand__c = 200;
        cic1.Stock_Point__c = StockPt2.id;
        insert cic1;
        
                    
        Component_Movement_Table__c CompMove = new Component_Movement_Table__c();
        CompMove.RecordTypeId = cmtrtMap.get('Inward Movement').getRecordTypeId();
        CompMove.Type_of_receipt__c = 'Service Center';
        CompMove.Component_Status__c = 'Usable';
        CompMove.Quantity__c = 10;
        CompMove.Quantity_2__c = 20;
        CompMove.Quantity_3__c = 30;
        CompMove.Quantity_4__c = 40;  
        CompMove.OwnerID=u.id;
        CompMove.Select_Component__c = prod.id;
        CompMove.Select_Component_2__c = prod1.id;
        CompMove.Select_Component_3__c = prod2.id;
        CompMove.Select_Component_4__c = prod3.id;
        compMove.Cancelled__c = False;
        CompMove.Received_from_Stock_Point__c = StockPt1.Id;
        CompMove.Stock_Point_Type__c = 'Service Engineer';
        CompMove.Product_Code_1__c ='1234';
        CompMove.Product_Code_2__c ='10012';
        CompMove.Product_Code_3__c ='12414';
        CompMove.Product_Code_4__c ='12400';
        Insert CompMove;
        
        
       
        
    }
    

}