src/objects/Component_Movement_line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Component_Movement_Table__c</fullName>
        <label>Component Movement Table</label>
        <referenceTo>Component_Movement_Table__c</referenceTo>
        <relationshipLabel>Component Movement line Items</relationshipLabel>
        <relationshipName>Component_Movement_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Select_Component__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Component Movement line Items</relationshipLabel>
        <relationshipName>Component_Movement_line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Movement line Item</label>
    <nameField>
        <displayFormat>TLID-{0000000}</displayFormat>
        <label>Component Movement line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Movement line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Generate_Invoice_Bill_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Invoice &amp; Bill No.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPONENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>COMPONENT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProductSalesCtrl.cls
public class ProductSalesCtrl {
    
    public Component_Movement_Table__c cmtRecord {get; set;}
    public List<LineItemWrapper> lineItemWrapList {get; set;}
    public Integer numberOfRows {get; set;}
    public Boolean showTable {get; set;}
    
    public productSalesCtrl() {
        cmtRecord = new Component_Movement_Table__c();
        Schema.RecordTypeInfo rtByName = Schema.SObjectType.Component_Movement_Table__c.getRecordTypeInfosByName().get('Product Sale');
        cmtRecord.RecordTypeId = rtByName.getRecordTypeId();
        lineItemWrapList = new List<LineItemWrapper>();
        numberOfRows = 1;
        addRow();
    }
    
    public void GetProductCategory()
    {
    
        Set<Id> prodIds = new Set<Id>();
        prodIds.add(lineItemWrapList[0].cmtliRecord.Select_Component__c);
        system.debug('GetCateg++++++'+lineItemWrapList[0].cmtliRecord.Select_Component__c);
        
        //Map<Id, Product__c> mapProduct = new Map<Id, Product__c>([select Product_Category__c from Product__c where id in :prodIds]);        
        Product__c objProduct = [select Product_Category__c from Product__c where id in :prodIds];
            
        if( objProduct != null ) {
          cmtRecord.Product_Category__c = objProduct.Product_Category__c;
             //ApexPages.addMessage(new Apexpages.Message(ApexPAges.Severity.ERROR, objProduct.Product_Category__c));              
          
                           }
                           
    }
    
    public PageReference addRow() {
        
        Integer rownum = lineItemWrapList.size();
        Integer endlimit = 1;
        if(numberOfRows != null && numberOfRows != 0) {
            endlimit = numberOfRows;
            for(Integer i = (rownum + 1); i <= (rownum + endlimit); i++) {
                lineItemWrapList.add(new LineItemWrapper(i, new Component_Movement_line_Item__c()));
            }
        }
        if(lineItemWrapList != null && lineItemWrapList.size() > 0) {
            showTable = true;
        }
        numberOfRows = 1;
        return null;
    }
    
    public PageReference removeRow(){
        String indx = ApexPages.currentPage().getParameters().get('indx');      
        Integer indxnum = Integer.valueOf(indx);
        lineItemWrapList.remove(indxnum - 1);
        
        if(indxnum - 1 < lineItemWrapList.size()){
            for(Integer i = (indxnum - 1); i < lineItemWrapList.size(); i++) {
               lineItemWrapList[i].index = i + 1; 
            } 
        }
        if(lineItemWrapList == null || lineItemWrapList.size() == 0) {
            showTable = false;
        }
        return null;
    }
    
    public PageReference doSave() {
      
        if(lineItemWrapList == null || lineItemWrapList.size() == 0) {
            ApexPages.addMessage(new Apexpages.Message(ApexPAges.Severity.ERROR, 'Please add atleast one Product.'));
            return null;
        }
            
        try {
            if(cmtRecord != null)
                upsert cmtRecord;
        } catch(Exception e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        Set<Id> prodIds = new Set<Id>();
        for(LineItemWrapper wrap :lineItemWrapList) {
            if(prodIds != null && prodIds.contains(wrap.cmtliRecord.Select_Component__c)) {
                ApexPages.addMessage(new Apexpages.Message(ApexPAges.Severity.ERROR, 'Product should not be repeated in line items.'));  
                return null;
            } else {
                prodIds.add(wrap.cmtliRecord.Select_Component__c);
            }
        }
        
        Map<Id, Product__c> mapProduct = new Map<Id, Product__c>([select Product_Category__c from Product__c where id in :prodIds]);
        
        List<Component_Movement_line_Item__c> lineItemList = new List<Component_Movement_line_Item__c>();
        
        for(LineItemWrapper wrap :lineItemWrapList) {
            if(wrap.cmtliRecord.Component_Movement_Table__c == null)
                wrap.cmtliRecord.Component_Movement_Table__c = cmtRecord.id;
            
           if( mapProduct != null && mapProduct.containsKey(wrap.cmtliRecord.Select_Component__c) && 
                   cmtRecord.Product_Category__c == mapProduct.get(wrap.cmtliRecord.Select_Component__c).Product_Category__c) {
               lineItemList.add(wrap.cmtliRecord);
           } else {
               ApexPages.addMessage(new Apexpages.Message(ApexPAges.Severity.ERROR, 'Product Category of all products should be "' + cmtRecord.Product_Category__c + '" as selected in Information section.'));  
               return null;
           }
              
        }
        try {
            if(lineItemList != null && lineItemList.size() > 0) {
                insert lineItemList;
                cmtRecord.Generate_Invoice_Bill_No__c = true;
                update cmtRecord;
            }    
            
        } catch(Exception e) {
            ApexPages.addMessages(e);
            return null;
        }
        return new PageReference('/' + cmtRecord.id);
    }
    
    public PageReference doCancel() {
        return new PageReference('/' + objectKeyPrefix());
    }
    
    public String objectKeyPrefix() {
      String prefix = Component_Movement_Table__c.SObjectType.getDescribe().getKeyPrefix();
      return prefix;
  } 
      
    public class LineItemWrapper {       
        public Component_Movement_line_Item__c cmtliRecord {get;set;}
        public Integer index {get;set;}
        
        public LineItemWrapper(Integer index, Component_Movement_line_Item__c cmtliRecord) {           
            this.index = index;
            this.cmtliRecord = cmtliRecord;
        }   
    }   
}