src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Transferred_to_Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transferred to Stock Point</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch, Service Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table (Transferred to Stock Point)</relationshipLabel>
        <relationshipName>R00N90000003PMFBEA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice_Component_Movement__c.object
<CustomObject>
    <fields>
        <fullName>Component_Movement_Table__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component Movement Table</label>
        <referenceTo>Component_Movement_Table__c</referenceTo>
        <relationshipLabel>Invoice Component Movement</relationshipLabel>
        <relationshipName>Invoice_Component_Movement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Invoice_No__c</fullName>
        <label>Full Invoice No</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoive_Number__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoive Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Invoice Component Movement</label>
    <nameField>
        <label>Invoice Component Movement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Component Movement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GenerateInvoiceComponentMovement.cls
public class GenerateInvoiceComponentMovement{

   public wrapperInvoiceCompMov WObj{get;set;}
 
    public GenerateInvoiceComponentMovement() {
        
        
    }
    
    public void GetInvoiceDetails()
    {
      string InvId = ApexPages.CurrentPage().getParameters().get('id');
      Component_Movement_Table__c SRObj = [Select id,CreatedBy.City__c,Transferred_to_Stock_Point__r.Name from Component_Movement_Table__c where id =:InvId];
      List<Invoice_Component_Movement__c> lstInv = [SELECT id,Component_Movement_Table__c ,Invoive_Number__c,Full_Invoice_No__c  from Invoice_Component_Movement__c where Component_Movement_Table__c =: SRObj.id];
      if(lstInv.size()<=0)
      {
        Invoice_Component_Movement__c objINV = [SELECT id,Component_Movement_Table__c ,Invoive_Number__c,Full_Invoice_No__c from Invoice_Component_Movement__c ORDER BY Id DESC LIMIT 1];
        
        integer iNo = integer.valueof(objINV.Invoive_Number__c)+1;
        
        string sFullInvoiceNo = '13-14/CC/'+ SRObj.Transferred_to_Stock_Point__r.Name + '/' + iNo ;
       
        WObj = new wrapperInvoiceCompMov(SRObj ,sFullInvoiceNo );
        
        //Insert new record in invoice table
          Invoice_Component_Movement__c  objI = new Invoice_Component_Movement__c();
          objI.Component_Movement_Table__c  = InvId;
          objI.Full_Invoice_No__c = sFullInvoiceNo ;
          Insert objI ;
      }
      else
      {
        //Invoice already created
        // ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Invoice already generated for this service request.');
        WObj = new wrapperInvoiceCompMov (SRObj ,lstInv[0].Full_Invoice_No__c);
        
      }
    }
    
    
    public class wrapperInvoiceCompMov {
       public Component_Movement_Table__c  SRObj{get;set;}
       public string InvoiceNo{get;set;}
       
       public wrapperInvoiceCompMov(Component_Movement_Table__c  sr,string sInvNo)
       {
         SRObj = sr;
         InvoiceNo = sInvNo;
         
       }
    
    }
}