src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Code__c</fullName>
        <formula>Select_Component__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Component Code 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Status__c</fullName>
        <label>Component Status</label>
        <picklist>
            <picklistValues>
                <fullName>Usable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Defective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity1__c</fullName>
        <label>Defective Quantity1</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity2__c</fullName>
        <label>Defective Quantity2</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity3__c</fullName>
        <label>Defective Quantity3</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity4__c</fullName>
        <label>Defective Quantity4</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Org__c</fullName>
        <label>From Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_2__c</fullName>
        <label>Quantity 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_3__c</fullName>
        <label>Quantity 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_4__c</fullName>
        <label>Quantity 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity1__c</fullName>
        <label>Received Quantity1</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity2__c</fullName>
        <label>Received Quantity2</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity3__c</fullName>
        <label>Received Quantity3</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity4__c</fullName>
        <label>Received Quantity4</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Select_Component_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 2</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 2)</relationshipLabel>
        <relationshipName>Components_Movement_Table2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 3</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 3)</relationshipLabel>
        <relationshipName>Components_Movement_Table3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Select Component 4</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 4)</relationshipLabel>
        <relationshipName>Components_Movement_Table4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_Transfer_Status__c</fullName>
        <label>Stock Transfer Status</label>
        <picklist>
            <picklistValues>
                <fullName>Outward Movement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Transit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transferred_to_Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transferred to Stock Point</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch, Service Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Components Movement Table (Transferred to Stock Point)</relationshipLabel>
        <relationshipName>R00N90000003PMFBEA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Transfer__c</fullName>
        <label>Type of Transfer</label>
        <picklist>
            <picklistValues>
                <fullName>Stock Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Service Engineer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_in_Hand__c</fullName>
        <label>Defective Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Service_Center_Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <recordTypes>
        <fullName>ServiceEngineer</fullName>
        <active>true</active>
        <label>Service Engineer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ComponentMovementTest2.cls
@isTest
public class ComponentMovementTest2{
    static testMethod void ComponentMovementTestMethod2(){ 
        try{
        Product__c Prod = new Product__c();
        Prod.name = 'Test';
        Prod.Product_Code__c = '1001';
        
        Prod.Is_Active__c = True;
        Prod.UoM__c = 'Set';
        Insert Prod;
        
        Product__c Prod1 = new Product__c();
        Prod1.name = 'Test1';
        Prod1.Product_Code__c = '1002';
       
        Prod1.Is_Active__c = True;
        Prod1.UoM__c = 'Set';
        Insert Prod1;
        
        Price_Books__C PriceBk = new Price_Books__C();
        PriceBk.Name = 'Carry In Service Charges';
        PriceBk.Description__c = 'Carry In Service Charges';
        PriceBk.IsActive__c = True;
        Insert PriceBk;
        
        Price_Book_Entry__c StdPBEntry = new Price_Book_Entry__c();
        
        StdPBEntry.UnitPrice__c = 1000;
        StdPBEntry.IsActive__c = True;
        StdPBEntry.Product__c = Prod.Id;
        StdPBEntry.Price_book__c = [Select Id from Price_book__c where Name = 'Standard Price Book' Limit 1].Id;
        Insert StdPBEntry;
        
        Price_Book_Entry__c PBEntry = new Price_Book_Entry__c();
       
        PBEntry.UnitPrice__c = 100;
        PBEntry.IsActive__c = True;
        PBEntry.Product__c = Prod.Id;
        PBEntry.Price_book__c = PriceBk.Id;
        Insert PBEntry;
        
        User[] Usr = [Select Id from User where Profile.name='Service Center' and IsActive=True Limit 2];
        
        User u = Usr[0];
        User u2 = Usr[1];              
         
             
            
        /*Current_Inventory_Component__c InTransitInventory = new Current_Inventory_Component__c();
        InTransitInventory.Stock_Point__c = [Select Id from Stock_point__c where Service_Center_Description__c = 'In Transit' Limit 1].Id;
        InTransitInventory.Component_Code__c = Prod.ProductCode;
        InTransitInventory.Name = Prod.Name;
        InTransitInventory.Usable_Quantity_in_hand__c = 500;
        InTransitInventory.Defective_Quantity_in_hand__c = 500;
        Insert InTransitInventory;*/
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
		Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
		Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Center');
		Id screctypeid = rtByName.getRecordTypeId();
		
		Schema.RecordTypeInfo rtByName1 =  rtMapByName.get('Service Engineer');
		Id serectypeid = rtByName1.getRecordTypeId();
		
        Stock_Point__c StockPt1 = new Stock_Point__c();
        StockPt1.RecordTypeId = screctypeid;  //[Select Id from RecordType where Name = 'Service Center' And SObjectType = 'Stock_Point__c'].Id;
        StockPt1.Service_Center_Description__c = 'TestCenter1';
        StockPt1.Service_Center_Address__c = 'Address1';
        StockPt1.Service_Center_Location_Code__c = '011';
        if(u2 != null){
            StockPt1.OwnerId = u2.Id;
        }
        Insert StockPt1;
        
        Current_Inventory_Component__c TempInventory = new Current_Inventory_Component__c();
        TempInventory.Stock_Point__c = StockPt1.Id;
        TempInventory.Component_Code__c = Prod.Product_Code__c;
        TempInventory.Name = Prod.Name;
        TempInventory.Usable_Quantity_in_hand__c = 500;
        TempInventory.Defective_Quantity_in_hand__c = 500;
        Insert TempInventory;
        
        System.runAs(u)
        {
            Stock_Point__c StockPt = new Stock_Point__c();
            StockPt.RecordTypeId = screctypeid;  //[Select Id from RecordType where Name = 'Service Center' And SObjectType = 'Stock_Point__c'].Id;
            StockPt.Service_Center_Description__c = 'TestCenter2';
            StockPt.Service_Center_Address__c = 'Address2';
            StockPt.Service_Center_Location_Code__c = '022';
            Insert StockPt;
            
            Stock_Point__c ServiceEngineer = new Stock_Point__c();
            ServiceEngineer.RecordTypeId = serectypeid;  //[Select Id from RecordType where Name = 'Service Engineer' And SObjectType = 'Stock_Point__c'].Id;
            ServiceEngineer.Service_Center_Description__c = 'TestEngineer';
            ServiceEngineer.Service_Center_Address__c = 'Address2';
            ServiceEngineer.Service_Center_Location_Code__c = '022';
            Insert ServiceEngineer;
            
            Current_Inventory_Component__c TempInventory2 = new Current_Inventory_Component__c();
            TempInventory2.Stock_Point__c = StockPt.Id;
            TempInventory2.Component_Code__c = Prod1.Product_Code__c;
            TempInventory2.Name = Prod1.Name;
            TempInventory2.Usable_Quantity_in_hand__c = 500;
            TempInventory2.Defective_Quantity_in_hand__c = 500;
            Insert TempInventory2;
            
            Current_Inventory_Component__c TempInventory3 = new Current_Inventory_Component__c();
            TempInventory3.Stock_Point__c = StockPt.Id;
            TempInventory3.Component_Code__c = Prod.Product_Code__c;
            TempInventory3.Name = Prod.Name;
            TempInventory3.Usable_Quantity_in_hand__c = 500;
            TempInventory3.Defective_Quantity_in_hand__c = 500;
            Insert TempInventory3;
            
            ///////////////////////////OUTWARD MOVEMENT//////////////////////////////////
            
            Schema.DescribeSObjectResult d2 = Schema.SObjectType.Component_Movement_Table__c;
			Map<String,Schema.RecordTypeInfo> rtMapByName2 = d2.getRecordTypeInfosByName();
			Schema.RecordTypeInfo rtByName2 =  rtMapByName2.get('Outward Movement');
			Id omrectypeid = rtByName2.getRecordTypeId();
			
			Schema.RecordTypeInfo rtByName3 =  rtMapByName2.get('Stock Inward');
			Id sirectypeid = rtByName3.getRecordTypeId();
			
            Id OutwardMovementRecordTypeId = omrectypeid;  //[Select Id from RecordType where Name = 'Outward Movement' and SObjectType = 'Component_Movement_Table__c' Limit 1].Id;
            //Scenario 4
            Component_Movement_Table__c CompMove4 = new Component_Movement_Table__c();
            CompMove4.RecordTypeId = OutwardMovementRecordTypeId;
            CompMove4.Type_of_transfer__c = 'Stock Transfer';
            CompMove4.Component_Status__c = 'Usable';
            CompMove4.Select_Component__c = Prod.Id;
            CompMove4.Quantity__c = 10;
            CompMove4.Select_Component_2__c = Prod.Id;
            CompMove4.Quantity_2__c = 10;
            CompMove4.Select_Component_3__c = Prod.Id;
            CompMove4.Quantity_3__c = 10;
            CompMove4.Select_Component_4__c = Prod.Id;
            CompMove4.Quantity_4__c = 10;
            CompMove4.Transferred_to_Stock_Point__c = StockPt1.Id;
            Insert CompMove4;
            
            //Scenario 4.1
            Component_Movement_Table__c CompMove41 = new Component_Movement_Table__c();
            CompMove41.RecordTypeId = OutwardMovementRecordTypeId;
            CompMove41.Type_of_transfer__c = 'Stock Transfer';
            CompMove41.Component_Status__c = 'Usable';
            CompMove41.Select_Component__c = Prod1.Id;
            CompMove41.Quantity__c = 10;
            CompMove41.Transferred_to_Stock_Point__c = StockPt1.Id;
            Insert CompMove41;
            
            //Scenario 4.1
            Component_Movement_Table__c CompMove42 = new Component_Movement_Table__c();
            CompMove42.RecordTypeId = OutwardMovementRecordTypeId;
            CompMove42.Type_of_transfer__c = 'Stock Transfer';
            CompMove42.Component_Status__c = 'Usable';
            CompMove42.Select_Component__c = Prod1.Id;
            CompMove42.Quantity__c = 10;
            CompMove42.Transferred_to_Stock_Point__c = StockPt1.Id;
            CompMove42.From_Org__c = '019-SC-GGN';
            Insert CompMove42;
            
            //Scenario 5
            Component_Movement_Table__c CompMove5 = new Component_Movement_Table__c();
            CompMove5.RecordTypeId = OutwardMovementRecordTypeId;
            CompMove5.Type_of_transfer__c = 'Transferred to Service Engineer';
            CompMove5.Component_Status__c = 'Usable';
            CompMove5.Select_Component__c = Prod.Id;
            CompMove5.Quantity__c = 10;
            CompMove5.Transferred_to_Stock_Point__c = ServiceEngineer.Id;
            Insert CompMove5;
            
            ///////////////////////////CANCELLATIONS//////////////////////////////////
            Id StockInwardRecordTypeId = sirectypeid;  //[Select Id from RecordType where Name = 'Stock Inward' and SObjectType = 'Component_Movement_Table__c' Limit 1].Id;
            if(u2 != null){ 
            System.runAs(u2)
            {
                CompMove4.RecordTypeId = StockInwardRecordTypeId;
                CompMove4.Received_Quantity1__c = 5;
                CompMove4.Defective_Quantity1__c = 5;
                CompMove4.Received_Quantity2__c = 5;
                CompMove4.Defective_Quantity2__c = 5;
                CompMove4.Received_Quantity3__c = 5;
                CompMove4.Defective_Quantity3__c = 5;
                CompMove4.Received_Quantity4__c = 5;
                CompMove4.Defective_Quantity4__c = 3;
                CompMove4.Stock_Transfer_Status__c = 'Received';
                //Update CompMove4;
                
                CompMove42.RecordTypeId = StockInwardRecordTypeId;
                CompMove42.Received_Quantity1__c = 5;
                CompMove42.Defective_Quantity1__c = 5;
                CompMove42.Stock_Transfer_Status__c = 'Received';
                Update CompMove42;
            }
            }
            CompMove5.Cancelled__c = True;
            Update CompMove5;
            
            
        
        }            
        
      }catch(Exception e)   
            {}   
    
    }
}