src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPONENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Service_Request__c</referenceTo>
        <relationshipLabel>Components Movement Table</relationshipLabel>
        <relationshipName>Components_Movement_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vat_Percentage__c</fullName>
        <label>Vat Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>COMPONENT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR CHARGE CONTROLLER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR PRODUCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENSET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Component_Tax_Rate_1__c</fullName>
        <label>Component Tax Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON-LINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>This will contain the names of the different states, branch email ids &amp; the details of managers &amp; accountants</description>
    <label>Branch Details</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch_Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VAT1__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPONENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ANDHRA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANDIGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHATTISGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GUJARAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HARYANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIMACHAL PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J&amp;K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JHARKHAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KARNATAKA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KERALA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MADHYA PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAHARASHTRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORISSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUNJAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAJASTHAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAMIL NADU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTTAR PRADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTTARAKHAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST BENGAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT_Percentage__c</fullName>
        <label>VAT Percentage</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>VAT</label>
    <nameField>
        <label>VAT Record  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_trgUp.cls
@isTest
public class Test_trgUp{
    public static testMethod void getCoverage()
    {
      String State = '';
      List<User> recordowner = [Select ID,State From User Where ID =: '00590000000cIQJ'];  
       if (recordowner != null && recordowner.Size()>0)
          State = recordowner[0].State; 
          
      List<Component_Movement_Table__c> lstCMT = [Select Id,Service_Request__c,Select_Component__c from Component_Movement_Table__c where Service_Request__c =: 'a05O0000001EugQIAS'];
      
      Product__c objProduct = [select Product_Category__c from Product__c where id =: lstCMT[0].Select_Component__c];
      List<VAT1__c> vats = new List<VAT1__c>();
      vats = [ SELECT ID,VAT_Percentage__c,Start_Date__c,End_Date__c FROM VAT1__c where State__c =:State 
                         AND Product_Category__c =: objProduct.Product_Category__c
                         
                   ];
     
     
     Service_Request__c  objSR = new Service_Request__c(id='a05O0000001EugQIAS');
     objSR.Component_Tax_Rate_1__c = vats[0].VAT_Percentage__c;
     update objSR;
    }


}