src/objects/Component_Movement_Table__c.object
<CustomObject>
    <description>All transactions related to movement of stocks between Stock Points</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Components Movement Table</relationshipLabel>
        <relationshipName>Components_Movement_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Select_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to select any stock type being transacted - component or finished good</inlineHelpText>
        <label>Select Component 1</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Components Movement Table (Select Component 1)</relationshipLabel>
        <relationshipName>Components_Movement_Table1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_Point_Type__c</fullName>
        <label>Stock Point Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Transfer__c</fullName>
        <label>Type of Transfer</label>
        <picklist>
            <picklistValues>
                <fullName>Stock Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Service Engineer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component Movement Table</label>
    <nameField>
        <displayFormat>TID-{0000000}</displayFormat>
        <label>Component Movement Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components Movement Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>AMC_Amount__c</fullName>
        <label>AMC Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AMC_Type__c</fullName>
        <label>AMC Type</label>
        <picklist>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Term__c</fullName>
        <label>Contract Term (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Done__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maintenance Done</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <label>Product Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Maintenance__c</fullName>
        <label>Total Maintenance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_PM__c</fullName>
        <label>No. Of PM</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TesttrgAMCPopulate.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TesttrgAMCPopulate {

    static testMethod void myUnitTest() 
    {
        try{
        // TO DO: implement unit test
        Account acc = new account();
        acc.name = 'test';
        insert acc;
        
        Product__c obj = new Product__c();
        obj.Name = 'Test Product';
        obj.Product_Code__c= '12345';
        obj.Is_Active__c = true;
        obj.UoM__c = 'Kg';
        obj.No_Of_PM__c = '4';
        insert obj;
        
              
        Contracts__c obj2 = new Contracts__c();
        obj2.Products__c = obj.id;
        obj2.AMC_Type__c = 'Comprehensive';
        obj2.Product_Quantity__c = 20;
        obj2.Account_Name__c = acc.id;
        //obj2.AMC_Amount__c = pbe.UnitPrice__c; 
        obj2.Total_Maintenance__c = 4;
        obj2.Next_Maintenance_Date__c = system.today();
        obj2.Contract_Term__c = 12;
        obj2.Maintenance_Done__c = 0;
        insert obj2;
        
        System.assert(obj.No_Of_PM__c == '4',obj2.Next_Maintenance_Date__c = system.today().addMonths(3));
        System.assert(obj.No_Of_PM__c == '3',obj2.Next_Maintenance_Date__c = system.today().addMonths(4));
        System.assert(obj.No_Of_PM__c == '2',obj2.Next_Maintenance_Date__c = system.today().addMonths(6));
        System.assert(obj.No_Of_PM__c == '1',obj2.Next_Maintenance_Date__c = system.today().addMonths(12));
        
        
        obj2.Maintenance_Done__c = 1;
        obj2.AMC_Type__c = 'Non-Comprehensive';
        update obj2;
        
        Component_Movement_Table__c obj5 = new Component_Movement_Table__c();
        obj5.Select_Component__c = obj.id;
        obj5.Type_of_Transfer__c = 'tstt';
        obj5.Cancelled__c = False;
        obj5.Stock_Point_Type__c ='Service Center';
        insert obj5;
        
        obj5.Cancelled__c = True;
        //update obj5;
        
        
        
       }catch(Exception e){}
        
    }
}