src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Activated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activated_Date__c</fullName>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActivateContractCtrl.cls
public class ActivateContractCtrl {

    public Contracts__c contractObj;
    
    public activateContractCtrl(ApexPages.StandardController ctrl) {
        contractObj = (Contracts__c)ctrl.getRecord();
    }
    
    public PageReference updateContract() {
        contractObj.Status__c = 'Activated';
        contractObj.Activated_By__c = UserInfo.getUserId();
        contractObj.Activated_Date__c = System.now();
        update contractObj;
        return new PageReference('/' + contractObj.id);
    }
}