src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Activated_Date__c</fullName>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stock_Point_Name__c</fullName>
        <label>Stock Point Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Contracts (Stock Point)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts</label>
        <referenceTo>Contracts__c</referenceTo>
        <relationshipLabel>Invoice Contract</relationshipLabel>
        <relationshipName>Invoice_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Invoice_No__c</fullName>
        <label>Full Invoice No</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoive_Number__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoive Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Invoice Contract</label>
    <nameField>
        <label>Invoice Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GenerateInvoiceContract.cls
public class GenerateInvoiceContract{

   public wrapperInvoiceContract WObj{get;set;}
   //public integer iCount{get;set;}
 
    public GenerateInvoiceContract() {
        
        
    }
    
    
    public void GetInvoiceDetails()
    {
      string InvId = ApexPages.CurrentPage().getParameters().get('id');
      try
      {
        
        //string asa = 'Select id,Stock_Point_Name__c ,Activated_Date__c,RecordTypeId  from Contracts__c where id = '+InvId+' and RecordTypeId in (SELECT Id FROM RecordType WHERE Name = \'Service Center\')';
        //system.debug('aaaaaaa'+asa);
        Contracts__c SRObj = [Select id,Stock_Point_Name__c ,Activated_Date__c,RecordTypeId  from Contracts__c where id =:InvId ];
        //Contracts__c SRObj = [Select id,Stock_Point_Name__c ,Activated_Date__c,RecordTypeId  from Contracts__c where id =:InvId and RecordTypeId in (SELECT Id FROM RecordType WHERE Name =: 'Service Center')];
        //Contracts__c SRObj = [Select id,CreatedBy.City__c,Stock_Point__c,Stock_Point__r.Name,Activated_Date__c,RecordTypeId  from Contracts__c where id =:InvId ];
          if(SRObj != null)
           {
             system.debug('hi');
              if(SRObj.Activated_Date__c != null)
              {
                      List<Invoice_Contract__c> lstInv = [SELECT id,Contracts__c,Invoive_Number__c,Full_Invoice_No__c  from Invoice_Contract__c where Contracts__c =: SRObj.id];
                      if(lstInv.size()<=0)
                      {
                        Invoice_Contract__c objINV = [SELECT id,Contracts__c,Invoive_Number__c,Full_Invoice_No__c from Invoice_Contract__c ORDER BY Id DESC LIMIT 1];
                        
                        integer iNo = integer.valueof(objINV.Invoive_Number__c)+1;
                        
                        string sStockPoint = '';
                        if(SRObj.Stock_Point_Name__c  != '')
                        {
                           sStockPoint = SRObj.Stock_Point_Name__c.SubString(0,3);
                        }
                        
                        string strYear = String.ValueOf(DateTime.Now().Year()).substring(2,4) + '-' + String.ValueOf(DateTime.Now().addYears(1).Year()).substring(2,4);
                        
                        string sFullInvoiceNo = strYear + '/AMC/'+ sStockPoint  + '/' + iNo ;
                       
                        WObj = new wrapperInvoiceContract(SRObj ,sFullInvoiceNo );
                        
                        //Insert new record in invoice table
                          Invoice_Contract__c objI = new Invoice_Contract__c();
                          objI.Contracts__c = InvId;
                          objI.Full_Invoice_No__c = sFullInvoiceNo ;
                          Insert objI ;
                      }
                      else
                      {
                        //Invoice already created
                        // ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Invoice already generated for this service request.');
                        WObj = new wrapperInvoiceContract(SRObj ,lstInv[0].Full_Invoice_No__c);
                        
                      }
              }
               
           }
        
       }
       catch(Exception e)
       {
         System.debug('--- Error Message ---' + e.getMessage());
       }
    }
    
    
    public class wrapperInvoiceContract{
       public Contracts__c  SRObj{get;set;}
       public string InvoiceNo{get;set;}
       
       public wrapperInvoiceContract(Contracts__c  sr,string sInvNo)
       {
        
         SRObj = sr;
         InvoiceNo = sInvNo;
        
       }
    
    }
}