src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Term__c</fullName>
        <label>Contract Term (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERP_Activated_Date__c</fullName>
        <formula>TEXT( DAY( DATEVALUE(  Activated_Date__c ) )) + &apos;-&apos; + 

CASE( MONTH( DATEVALUE(  Activated_Date__c ) ) , 
1, &apos;JAN&apos;, 
2, &apos;FEB&apos;, 
3, &apos;MAR&apos;, 
4, &apos;APR&apos;, 
5, &apos;MAY&apos;, 
6, &apos;JUN&apos;, 
7, &apos;JUL&apos;, 
8, &apos;AUG&apos;, 
9, &apos;SEP&apos;, 
10, &apos;OCT&apos;, 
11, &apos;NOV&apos;, 
12, &apos;DEC&apos;, 
&apos;&apos; 
) + &apos;-&apos; + 

TEXT(YEAR( DATEVALUE(  Activated_Date__c  ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP Activated Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_End_Date__c</fullName>
        <formula>TEXT( DAY(Contract_End_Date__c  ) ) + &apos;-&apos; + 

CASE( MONTH( Contract_End_Date__c ) , 
1, &apos;JAN&apos;, 
2, &apos;FEB&apos;, 
3, &apos;MAR&apos;, 
4, &apos;APR&apos;, 
5, &apos;MAY&apos;, 
6, &apos;JUN&apos;, 
7, &apos;JUL&apos;, 
8, &apos;AUG&apos;, 
9, &apos;SEP&apos;, 
10, &apos;OCT&apos;, 
11, &apos;NOV&apos;, 
12, &apos;DEC&apos;, 
&apos;&apos; 
) + &apos;-&apos; + 

TEXT(YEAR(  Contract_End_Date__c  ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP End Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Start_Date__c</fullName>
        <formula>TEXT( DAY(  Start_Date__c  ) ) + &apos;-&apos; + 

CASE( MONTH( Start_Date__c   ) , 
1, &apos;JAN&apos;, 
2, &apos;FEB&apos;, 
3, &apos;MAR&apos;, 
4, &apos;APR&apos;, 
5, &apos;MAY&apos;, 
6, &apos;JUN&apos;, 
7, &apos;JUL&apos;, 
8, &apos;AUG&apos;, 
9, &apos;SEP&apos;, 
10, &apos;OCT&apos;, 
11, &apos;NOV&apos;, 
12, &apos;DEC&apos;, 
&apos;&apos; 
) + &apos;-&apos; + 

TEXT(YEAR( Start_Date__c  ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP Start Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Done__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maintenance Done</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Products__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Ass__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Engineer Assigned</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.Service_Center_Location_Code__c</field>
                <operation>equals</operation>
                <valueField>$User.Stock_Point__c</valueField>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Engineer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Maintenance__c</fullName>
        <label>Total Maintenance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVERTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON-LINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Serial_No__c</fullName>
        <label>Product Serial No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON MAINS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM NOT WORKING ON BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAINS MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC MCB TRIPPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BLOWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUSE BROKEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWITCH FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM ON BUT NO OUTPUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM DEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS LOW BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER LOAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS SHORT CIRCUIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING CONTINUSELY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT CHARGING BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY OVERHEATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY DRY RUN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONNECTOR BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSIT DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSFORMER BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARD BURNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANGEOVER PROBLEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAN NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOOSE CONNECTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOCKET DAMAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAIN LEAD FAULTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED DISPLAY NOT WORKING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM SHOWS OVER TEMPERATURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BATTERY LOW BACKUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEM GENERATES HUMMING SOUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>038 - AMC VISIT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Engineer Assigned</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Stock_Point__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Stock_Point__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warranty_Status__c</fullName>
        <label>Warranty</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateCallOnContract.cls
global class CreateCallOnContract implements Database.Batchable<SObject>{
    global Database.QueryLocator start(Database.BatchableContext bi){
        //Date AMCStartDate_FirstQtr = System.Today().addMonths(-3);
        //return Database.getQueryLocator([Select id,Service_Engineer_Ass__c,Account_Name__c,Start_Date__c,ERP_Start_Date__c,ERP_End_Date__c,ERP_Activated_Date__c,Products__c,Product_Category__c,Product_Serial_No__c,Total_Maintenance__c,Contract_Term__c,Maintenance_Done__c from Contracts__c where Status__c =:'Activated' and Due_Maintenance_Date__c =: System.Today()]);
        return Database.getQueryLocator([Select id,Service_Engineer_Ass__c,Account_Name__c,Start_Date__c,ERP_Start_Date__c,ERP_End_Date__c,ERP_Activated_Date__c,Products__c,Product_Category__c,Product_Serial_No__c,Total_Maintenance__c,Contract_Term__c,Maintenance_Done__c,Next_Maintenance_Date__c from Contracts__c where  Next_Maintenance_Date__c =: System.Today()]);
    }

    global void execute(Database.BatchableContext bi, List<sObject> scope){
     if(scope.size()>0)
     {
       List<Contracts__c> contractList = (List<sObject>)scope; 
       List<Service_Request__c> lstSR = new List<Service_Request__c>();
       List<Contracts__c> lstUpdateContract = new List<Contracts__c>();
       for(Contracts__c con : contractList)
       {
         integer TotalMaintenance = Integer.valueOf(con.Contract_Term__c * con.Total_Maintenance__c / 12) ; 
         if(Integer.valueOf(con.Maintenance_Done__c) < TotalMaintenance)
         {
             Service_Request__c objSR = new Service_Request__c();
             objSR.Account__c = con.Account_Name__c;
             objSR.Status__c = 'New';
             objSR.Origin__c = 'Web';
             objSR.Reason__c = '038 - AMC VISIT';
             objSR.Warranty_Status__c = 'No';
             objSR.Products__c = con.Products__c;
             objSR.Product_Category__c = con.Product_Category__c;
             //objSR.Product_Code__c = con.Product_Serial_No__c ;
             objSR.Service_Engineer_Assigned__c = con.Service_Engineer_Ass__c;
             objSR.Complain_Type__c = 'ADDITIONAL SERVICE';
             objSR.CALL_TYPE__c = 'PM VISIT';
             objSR.AMC_Status__c = 'Yes';
             objSR.Warranty_Status__c = 'No';
             lstSR.add(objSR);
                  
             if(Integer.valueOf(con.Total_Maintenance__c) == 4 )
             {
               con.Next_Maintenance_Date__c =con.Next_Maintenance_Date__c.addMonths(3);
               date dObj =date.newInstance(con.Next_Maintenance_Date__c.year(),con.Next_Maintenance_Date__c.month(),con.Next_Maintenance_Date__c.day());
               con.Next_Maintenance_Date__c =  dObj ;
               con.Maintenance_Done__c  = con.Maintenance_Done__c + 1;
               lstUpdateContract.add(con);
             }
             if(Integer.valueOf(con.Total_Maintenance__c) == 3 )
             {
               con.Next_Maintenance_Date__c = con.Next_Maintenance_Date__c.addMonths(4);
               date dObj =date.newInstance(con.Next_Maintenance_Date__c.year(),con.Next_Maintenance_Date__c.month(),con.Next_Maintenance_Date__c.day());
               con.Next_Maintenance_Date__c =  dObj ;
               con.Maintenance_Done__c  = con.Maintenance_Done__c + 1;
               lstUpdateContract.add(con);
             }
             if(Integer.valueOf(con.Total_Maintenance__c) == 2 )
             {
               con.Next_Maintenance_Date__c = con.Next_Maintenance_Date__c.addMonths(6);
               date dObj =date.newInstance(con.Next_Maintenance_Date__c.year(),con.Next_Maintenance_Date__c.month(),con.Next_Maintenance_Date__c.day());
               con.Next_Maintenance_Date__c =  dObj ;
               con.Maintenance_Done__c  = con.Maintenance_Done__c + 1;
               lstUpdateContract.add(con);
             }
             if(Integer.valueOf(con.Total_Maintenance__c) == 1 )
             {
               con.Next_Maintenance_Date__c = con.Next_Maintenance_Date__c.addMonths(12);
               date dObj =date.newInstance(con.Next_Maintenance_Date__c.year(),con.Next_Maintenance_Date__c.month(),con.Next_Maintenance_Date__c.day());
               con.Next_Maintenance_Date__c =  dObj ;
               con.Maintenance_Done__c  = con.Maintenance_Done__c + 1;
               lstUpdateContract.add(con);
             }
         }
       }
       try
       {
          if(lstSR != null && lstSR.size() > 0) 
          insert lstSR;
          update lstUpdateContract;
       }
       catch(Exception e)
       {
         System.debug('--- Error Message ---' + e.getMessage());
       }
      } 
    }
    global void finish(Database.BatchableContext bi){       
    }
}