src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>AMC_Bill_No__c</fullName>
        <label>AMC Bill No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activated_Date__c</fullName>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Product_Category__c</field>
                <operation>notEqual</operation>
                <value>COMPONENT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_Point_Name__c</fullName>
        <label>Stock Point Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Contracts (Stock Point)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts</label>
        <referenceTo>Contracts__c</referenceTo>
        <relationshipLabel>Invoice Contract</relationshipLabel>
        <relationshipName>Invoice_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Contract</label>
    <nameField>
        <label>Invoice Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>BANGALORE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUBANESWAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHANDIGARH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHENNAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COCHIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEHRADUN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GHAZIABAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GURGAON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GUWAHATI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HYDERABAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDORE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAIPUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAMMU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KOLKATA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LUCKNOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LUDHIANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUMBAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAGPUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAIPUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RANCHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROHTAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VADODARA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIJAYAWADA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DESIGNATION__c</fullName>
        <label>Designation</label>
        <picklist>
            <picklistValues>
                <fullName>AREA SERVICE IN-CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AREA SERVICE IN-CHARGE (BATTERY)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSISTANT VICE PRESIDENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRANCH SERVICE IN-CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPUTY GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPUTY MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELECTRICIAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENGINEER - TESTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE - AUDIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXECUTIVE - CALL CENTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GENERAL MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELPER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REGIONAL SERVICE MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REGIONAL TRAINING SPECILIEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE COORDINATOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - BATTERY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - GEN SET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - HIGH CAPACITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - LOW CAPACITY</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - SOLAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - TRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE ENGINEER - WAREHOUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. EXECUTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. MANAGER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. VICE PRESIDENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Center_Address__c</fullName>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Engineer_Id__c</fullName>
        <inlineHelpText>Required Field . Should match Oracle AR Customer Number</inlineHelpText>
        <label>Service Engineer Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_InvoiceContract.cls
@isTest
//@isTest(SeeAllData=true)
Public Class test_InvoiceContract{

    public static testmethod void Invoice_no()
    {
        User u = new User(
             Alias =  'alia', 
             Email = 'test@sk.com',
             EmailEncodingKey = 'UTF-8', 
             LanguageLocaleKey = 'en_US', 
             LocalesIdKey = 'en_US', 
             TimeZonesIdKey = 'America/Los_Angeles',
             Username = 'test@sk.com',
             LastName = 'lname',
             CommunityNickname = 'cname',
             Stock_Point__c = '033-',
             ProfileId = [select id, Name from Profile where Name = 'CRM Branch User'].id
         );       
        
        insert u; 
        system.runas(u){

        Product__c Prod1 = new Product__c();
        Prod1.name = 'Test1';
        Prod1.Product_Code__c = '12345';
        Prod1.Is_Active__c = True;
        Prod1.UoM__c = 'Set';
        Prod1.CurrencyIsoCode = null;
        insert Prod1;
       
        Price_Books__c objPB = new Price_Books__c();
             objPB.Name='Standard Price Book';
             insert objPB;
         
       Price_Book_Entry__c objPBE =new Price_Book_Entry__c();
       objPBE.Product__c=Prod1.id;
       objPBE.Price_Book__c=objPB.id;
       objPBE.UnitPrice__c=200;
       insert objPBE;
       
       Schema.DescribeSObjectResult d = Schema.SObjectType.Stock_Point__c;
        Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('Service Engineer');
        Id stockId = rtByName.getRecordTypeId();
        
              
      Stock_Point__c objSP = new Stock_Point__c();
      objSP.RecordTypeId = stockId;
      objSP.OwnerId = u.Id;
      objSP.Name = 'XYZ';
      objSP.Service_Center_Description__c = 'TestCenter1';
      objSP.Service_Center_Address__c = 'Address1';
      objSP.Service_Center_Location_Code__c = '033-';
      objSP.DESIGNATION__c = 'HELPER';
      objSP.Service_Engineer_Id__c = 'H900113';
      objSP.Region__c = 'CENTRAL';
      objSP.Branch__c ='LUCKNOW';
      objSP.Active__c = true;
      insert objSP;
         
         Contracts__c SRObj = new Contracts__c();
         SRObj.Stock_Point_Name__c = '113-SC-JALANDHAR';
         SRObj.Activated_Date__c = datetime.newInstance(2008, 12, 1);
         SRObj.AMC_Bill_No__c='CON123';
         SRObj.Products__c = Prod1.id;
         SRObj.Product_Quantity__c = 1;
         SRObj.Product_Serial_No__c = 'NA';
         SRObj.AMC_Type__c = 'Comprehensive';
         SRObj.Payment_Option__c = 'Single Advance Payment';
         SRObj.Contract_Term__c = 12;
         SRObj.Service_Engineer_Ass__c = objSP.id;
         SRObj.Start_Date__c = date.newInstance(2008, 12, 1);//date.parse('2013-04-10');
         SRObj.Stock_Point_Name__c = '113-SC-JALANDHAR';
         insert SRObj;
         
         System.assert(SRObj != null);
      
         apexpages.currentpage().getparameters().put('id' , SRObj.id);
           
         /*List<Invoice_Contract__c>lstInv = new List<Invoice_Contract__c>();
         for(integer i =2;i<7;i++)
         {
           Invoice_Contract__c objINV = new Invoice_Contract__c();
           objINV.Contracts__c = SRObj.id ;
           objINV.Full_Invoice_No__c = '13-14/AMC/'+i ;
           lstInv.add(objINV);
         }        
         insert lstInv;*/
                
                           
         //Invoice_Contract__c objINV2 = [SELECT id,Contracts__c,Invoive_Number__c,Full_Invoice_No__c from Invoice_Contract__c ORDER BY Id DESC LIMIT 1];                 
         //System.assert(objINV2 != null);
         
         Invoice_Contract__c objINV = new Invoice_Contract__c();
         objINV.Contracts__c = SRObj.id ;
         objINV.Full_Invoice_No__c = '13-14/AMC/0067' ;
         insert objINV;
         //update objINV;
      
         GenerateInvoiceContract objgetInvoice = new GenerateInvoiceContract();
         objgetInvoice.GetInvoiceDetails();
         GenerateInvoiceContract.wrapperInvoiceContract objwrapperInvoiceContract = new GenerateInvoiceContract.wrapperInvoiceContract(SRObj,'13-14/AMC/0067');
         //objgetInvoice.WObj = objwrapperInvoiceContract ;
       
       }
    }  
}