src/objects/Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <label>Product Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestOverrideCtrl.cls
@IsTest
   public class TestOverrideCtrl{
     static testMethod void ContractOverrideCtrlTestMethod(){
        Contracts__c objCon = new Contracts__c(
           //LastName = 'ff'
           //Description__c = ' hghjg'
           Product_Quantity__c=488
         );
         insert objCon;
        
        ApexPages.StandardController cont = new ApexPages.StandardController(objCon);
        ContractOverrideCtrl actCOn = new ContractOverrideCtrl(cont);
        actCOn.srRedirect();
     }
     
    static testMethod void CaseOverrideCtrlTestMethod(){
        
       Profile c= [select Name from Profile  where Name = 'Standard User' limit 1];
        
        //list<Service_Request__c> srlst=new list<Service_Request__c>();
        Service_Request__c oljCon = new Service_Request__c(
           // Status__c = 'Closed'
          
         );
        try{
            insert oljCon;
            
           }catch(Exception e){} 
         System.debug('===oljCon===' +oljCon);
        // srlst.add(oljCon);
         
         
         ApexPages.StandardController cont = new ApexPages.StandardController(oljCon);
         CaseOverrideCtrl aactCOn = new CaseOverrideCtrl(cont);
         aactCOn.srRedirect();
     }
     
    
  }