src/objects/Current_Inventory_Component__c.object
<CustomObject>
    <description>Updated Stock Status of Inventory at all Stock Points</description>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Defective_Quantity_in_Hand__c</fullName>
        <label>Defective Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Point</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipName>R00N20000001R4tEEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usable_Quantity_in_Hand__c</fullName>
        <label>Usable Quantity in Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Current Stock</label>
    <nameField>
        <label>Component Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Current Stock</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Service_Center_Location_Code__c</fullName>
        <label>Location Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testclass.cls
public class testclass{



    String ErrMsg;

    String ErrMail;

    String SC_Code;

    Id TempAddSPId;

    Current_Inventory_Component__c NewCurInv = new Current_Inventory_Component__c();

    Map<String, Double> StockTransferPriceMap = new Map<String, Double>();

    

    public void AddbyOwner(String ProdName, String ProdCode, Id OwnId, String CompStatus, Double Qty){

        //The below query retrieves the Inventory record to which

        //quantity has to be added
		Component_Movement_Table__Share Share = new Component_Movement_Table__Share();   
        Current_Inventory_Component__c[] RecordToAdd = [Select Name, Usable_Quantity_in_Hand__c, 

        Defective_Quantity_in_Hand__c, Stock_Point__r.Id, Stock_Point__r.Service_Center_Location_Code__c from Current_Inventory_Component__c where

        Stock_Point__r.OwnerId = :OwnId and Stock_Point__r.RecordType.Name = 'Service Center' and Component_code__c = :ProdCode];              

        If(RecordToAdd.size()>0)

        {   
            SC_Code = RecordToAdd[0].Stock_Point__r.Service_Center_Location_Code__c;
        }
         Else

        {
        	  
        	  Stock_Point__c StockPt = [Select Id, Service_Center_Location_Code__c 
        	  from Stock_Point__c where 
        	  OwnerId = :OwnId and 
        	  RecordType.Name='Service Center' Limit 1];             
        	
        
        }

    }

    static testMethod void dotest(){
        testclass obj = new testclass();
        List<RecordType> rt = [select id,name from recordtype where name =: 'Service Center'];        
        Stock_Point__c s = new Stock_Point__c(recordtypeid=rt[0].id);
        insert s;
        
		obj.AddbyOwner('abc', 'acv', Userinfo.getUserId(), '', 2);  
    }         

}