src/objects/Indent_Request__c.object
<CustomObject>
    <description>Indent Request</description>
    <fields>
        <fullName>Dispatch_Sts__c</fullName>
        <label>Dispatch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requisition_Date__c</fullName>
        <label>Requisition Date</label>
        <type>Date</type>
    </fields>
    <label>Indent Request</label>
    <nameField>
        <label>Indent No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indent Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Indent_Request_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Quantity__c</fullName>
        <label>Approved Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indent_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indent Request</label>
        <referenceTo>Indent_Request__c</referenceTo>
        <relationshipLabel>Indent Request Details</relationshipLabel>
        <relationshipName>Indent_Request_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Products__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Indent Request Details</relationshipLabel>
        <relationshipName>Indent_Request_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Quantity__c</fullName>
        <label>Requested Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Indent Request Detail</label>
    <nameField>
        <label>Sl No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indent Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indent_Request_Dispatch_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Quantity__c</fullName>
        <formula>Indent_Request_Detail__r.Approved_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approved Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dispatch_Date__c</fullName>
        <label>Dispatch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dispatch_Quantity__c</fullName>
        <label>Dispatch Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indent_Request_Detail__c</fullName>
        <label>Indent Request Detail</label>
        <referenceTo>Indent_Request_Detail__c</referenceTo>
        <relationshipLabel>Indent Request Dispatch Details</relationshipLabel>
        <relationshipName>Indent_Request_Dispatch_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indent Request Dispatch Detail</label>
    <nameField>
        <label>Dispatch No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indent Request Dispatch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <picklist>
            <picklistValues>
                <fullName>Ea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MyTest.cls
@isTest
private class MyTest
{ 
    private static testmethod void test1()
    {       
        Product__c prod = new Product__c();
        prod .Name = 'Test Product';
        prod .Product_Code__c= '12345';
        prod .Is_Active__c = true;
        prod .UoM__c = 'Kg';
        insert prod ;
        
        Indent_Request__c indentObj = new Indent_Request__c();
        indentObj.Requisition_Date__c = Date.today();
        indentObj.Dispatch_Sts__c = 'Pending';
        insert indentObj;
        
        Indent_Request_Detail__c det1 = new Indent_Request_Detail__c();
        det1.Requested_Quantity__c = 5;
        det1.Approved_Quantity__c = 5;
        det1.Products__c = prod.Id;
        det1.Indent_Request__c = indentObj.Id;
        insert det1; 
        
        
        Indent_Request_Dispatch_Detail__c dispatch1 = new Indent_Request_Dispatch_Detail__c();
        dispatch1.Indent_Request_Detail__c = det1.Id;
        dispatch1.Dispatch_Date__c = Date.today();
        dispatch1.Dispatch_Quantity__c = 1;
        insert dispatch1;
        
        
        Stock_Point__c spObj = new Stock_Point__c();
        spObj.Name = 'Sourav Trial';
        spObj.OwnerId = Userinfo.getUserId();
        insert spObj;
        
        ApexPages.StandardController stdcont = new ApexPages.StandardController(indentObj);
        IndentRequestController ircObj = new IndentRequestController(stdcont);
               
        PageReference page1 = new PageReference('/apex/IndentRequestForm?Id=' + indentObj.Id);
        test.setCurrentPage(page1);
        
        ircObj = new IndentRequestController(stdcont);
        
        ircObj.cancel();
        ircObj.addLineItems();
        ircObj.deletedItem = 0;
        ircObj.onDelete();
        ircObj.saveIndentRequest();
        
        det1 = new Indent_Request_Detail__c();
        det1.Requested_Quantity__c = 5;
        det1.Approved_Quantity__c = 5;
        det1.Products__c = prod.Id;
        det1.Indent_Request__c = indentObj.Id;
        insert det1;
        
        Indent_Request_Dispatch_Detail__c dispatch2 = new Indent_Request_Dispatch_Detail__c();        
        dispatch2.Indent_Request_Detail__c = det1.Id;
        dispatch2.Dispatch_Date__c = Date.today();
        dispatch2.Dispatch_Quantity__c = 3;
        insert dispatch2;
        
        Indent_Request_Dispatch_Detail__c dispatch3 = new Indent_Request_Dispatch_Detail__c();        
        dispatch3.Indent_Request_Detail__c = det1.Id;
        dispatch3.Dispatch_Date__c = Date.today();
        dispatch3.Dispatch_Quantity__c = 3;
        
        ViewIndentExtension vieObj = new ViewIndentExtension(stdcont);
        vieObj.itemIndex = 0;
        vieObj.handleCollapse();
        vieObj.editBtnHandler();
        vieObj.cancelBtnHandler();
        vieObj.pendingBtnHandler();
        vieObj.approveBtnHandler();
        vieObj.dispatchBtnHandler();
        vieObj.setFlags();
        
        vieObj.save();        
        
        vieObj.cancel();
        vieObj.createFilteredDetailList();
        
        ViewIndentExtension.ItemDetail obj = new ViewIndentExtension.ItemDetail();
        obj.detailObj = det1;
        obj.dispatchDetailObj = dispatch3;
        
        List<ViewIndentExtension.ItemDetail> filList = new List<ViewIndentExtension.ItemDetail>();
        filList.add(obj);
        vieObj.itemDetailFilteredList = filList;
        
        vieObj.saveDispatch();
        vieObj.cancelDispatch();      
        
    } 
   
}