src/objects/Inventory__c.object
<CustomObject>
    <description>Dummy -Inventory</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Code__c</fullName>
        <label>ERP Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Inventory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>This object is being used for SuKAM PRM PROJECT</description>
    <fields>
        <fullName>Model__c</fullName>
        <description>This wil contain the product model used for Su-Kam PRM</description>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Despatch__c.object
<CustomObject>
    <description>This will contain fields for order despatches</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <formula>Order_Line_Item__r.Capacity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Capacity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Code__c</fullName>
        <description>This will contain the ERP code that is maintained for every order line item</description>
        <formula>Order_Line_Item__r.ERP_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Order_Line_Item__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <label>Order Despatch</label>
    <nameField>
        <label>Despatch No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Despatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <description>This will contain the details for every order line item</description>
    <fields>
        <fullName>Basic__c</fullName>
        <label>Basic</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>This contains the capacity details of every product model</description>
        <label>Capacity</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Code__c</fullName>
        <label>ERP Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <description>This contains the product model name</description>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Product Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Code__c</fullName>
        <description>This will contain the ERP code for every product model</description>
        <externalId>true</externalId>
        <label>ERP Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book_Name__c</fullName>
        <label>Price Book Name</label>
        <picklist>
            <picklistValues>
                <fullName>Andaman and Nicobar Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dadra and Nagar Haveli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daman and Diu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haryana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Himachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammu and Kashmir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jharkhand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnataka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kerala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakshadweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meghalaya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mizoram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagaland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Capital Territory of Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Puducherry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Punjab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rajasthan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sikkim</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Code__c</fullName>
        <label>Reference Code</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>basic__c</fullName>
        <label>basic</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Price_Book_Name__c</fullName>
        <description>This contains the name of the state which in turn will decide which price book will be used for the partner users</description>
        <label>Price Book Name</label>
        <picklist>
            <picklistValues>
                <fullName>Andaman and Nicobar Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dadra and Nagar Haveli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daman and Diu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haryana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Himachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammu and Kashmir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jharkhand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnataka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kerala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakshadweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meghalaya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mizoram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagaland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Capital Territory of Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Puducherry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Punjab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rajasthan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sikkim</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_trgDespatch.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_trgDespatch {

    static testMethod void trgDespatchUnitTest() {
      Price_Book__c priceBookEntry=new Price_Book__c();
      priceBookEntry.Category__c='testCategory';
      priceBookEntry.model__c='testModel';
      priceBookEntry.Capacity__c='testCapacity';
      priceBookEntry.basic__c=1000.0;
      priceBookEntry.Reference_Code__c='testRefCode';
      priceBookEntry.price_book_name__c='Andhra Pradesh';
      priceBookEntry.ERP_Code__c='ERPcodeTest';
       insert priceBookEntry;
      
      State__c thisState=new State__c();
      
      thisState.State_Name__c='Andhra Pradesh';
      
      insert thisState;
      
      Profile oProfile = [SELECT Id 
	   					   FROM profile 
	   					   WHERE name='System Administrator']; 
      
      User oUser = new User(alias = 'standt', 
      	email='standarduser@testorg.com1', 
        emailencodingkey='UTF-8',
        lastname='Testing',
        languagelocalekey='en_US', 
        localesidkey='en_US', 
        profileid = oProfile.Id,
        timezonesidkey='America/Los_Angeles',
        username='standarduser209@testorg.com');
      insert oUser;
      
      Order__c ord = new Order__c();
      ord.Order_Date_Time__c=System.now();
      ord.Order_Status__c='Draft';
      ord.OwnerId = oUser.Id;
      insert ord;
      
      Order_Line_Item__c ordLineItem = new  Order_Line_Item__c();
      ordLineItem.Product_Category__c=priceBookEntry.category__c;
      ordLineItem.model__c=priceBookEntry.model__c;
      ordLineItem.capacity__c=priceBookEntry.capacity__c;
      ordLineItem.order_quantity__c=10;
      ordLineItem.ERP_Code__c = '1245898';
      ordLineItem.Order__c = ord.Id; 
      insert ordLineItem;
      
      Order_Despatch__c orderDespatch = new Order_Despatch__c();
      orderDespatch.Despatch_Date__c = Date.today();
      orderDespatch.Despatch_Quantity__c = 15;
      orderDespatch.Goods_Received__c = true;
      orderDespatch.Order_Line_Item__c = ordLineItem.Id; 
      insert orderDespatch;
      
      orderDespatch = [SELECT ID, Despatch_Quantity__c, Goods_Received__c FROM Order_Despatch__c Where Id =: orderDespatch.Id];
      orderDespatch.Despatch_Quantity__c = 150;
      update orderDespatch;
      
      orderDespatch = [SELECT ID, Despatch_Quantity__c, Goods_Received__c FROM Order_Despatch__c Where Id =: orderDespatch.Id];
      orderDespatch.Despatch_Quantity__c = 160;
      update orderDespatch;  
      
      
      
      /*List<Inventory__c> invObj = [Select Id from Inventory__c Where 
      							ERP_Code__c =: ordLineItem.ERP_Code__c];
      System.debug(orderDespatch.ERP_Code__c + 'inventroyDetails' + invObj);
      
      orderDespatch = new Order_Despatch__c();
      orderDespatch.Despatch_Date__c = Date.today();
      orderDespatch.Despatch_Quantity__c = 15;
      orderDespatch.Goods_Received__c = true;
      orderDespatch.Order_Line_Item__c = ordLineItem.Id; 
      insert orderDespatch;  
      
       
      orderDespatch = [SELECT ID, Despatch_Quantity__c, Goods_Received__c FROM Order_Despatch__c Where Id =: orderDespatch.Id];
      orderDespatch.Despatch_Quantity__c = 150;
      update orderDespatch;
      
      orderDespatch = new Order_Despatch__c();
      orderDespatch.Despatch_Date__c = Date.today();
      orderDespatch.Despatch_Quantity__c = 15;
      orderDespatch.Goods_Received__c = true;
      orderDespatch.Order_Line_Item__c = ordLineItem.Id; 
      insert orderDespatch;    	

	  invObj = [Select Id, Quantity__c from Inventory__c Where 
      							ERP_Code__c =: ordLineItem.ERP_Code__c];
      System.debug(orderDespatch.ERP_Code__c + 'inventroyDetails' + invObj);*/
	  	      						
      
      
    }
}