src/objects/Invoice_No__c.object
<CustomObject>
    <fields>
        <fullName>Full_Invoice_No__c</fullName>
        <label>Full Invoice No</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoive_Number__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>Invoive Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Service_Request__c</referenceTo>
        <relationshipLabel>Invoice No</relationshipLabel>
        <relationshipName>Invoice_No</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice No</label>
    <nameField>
        <label>Invoice No Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice No</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Centre_City__c.object
<CustomObject>
    <description>This object will contain the names of the cities &amp; the related service centres.</description>
    <fields>
        <fullName>Code__c</fullName>
        <displayFormat>CM-{000}</displayFormat>
        <externalId>true</externalId>
        <label>Code</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Service_Centre_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Centre Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Centre_City</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Centre City</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centre City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Component_Bill_No__c</fullName>
        <label>Component Bill No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Charges__c</fullName>
        <label>Component Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Component_Tax_Rate_1__c</fullName>
        <label>Component Tax Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_in_Component_Charges__c</fullName>
        <label>Discount % in Component Charges</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_in_Service_Charges__c</fullName>
        <label>Discount % in Service Charges</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <formula>(Service_Charges_After_Tax__c  +  Total_Component_Amount_After_Tax__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Misc_Component_Charges_Remark__c</fullName>
        <label>Misc. Component Charges Remark</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Misc_Component_Charges__c</fullName>
        <label>Misc. Component Charges</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Misc_Service_Charges_Remark__c</fullName>
        <label>Misc. Service Charges Remark</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Basic_CC_Amount__c</fullName>
        <formula>( Component_Charges__c - Component_Charges__c * Discount_in_Component_Charges__c )+ Misc_Component_Charges__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Basic CC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Basic_SC_Amount__c</fullName>
        <formula>(Service_Charges__c  - Service_Charges__c  *  Discount_in_Service_Charges__c  )  +   Service_Charges_Other__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Basic SC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Receiving_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Receiving Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Bill_No__c</fullName>
        <label>Service Bill No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Centre_City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used by Call Center User to select the Service Center City</description>
        <label>Service Centre City</label>
        <referenceTo>Service_Centre_City__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Service_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Type__c</fullName>
        <label>Service Charge Type</label>
        <picklist>
            <controllingField>AMC_Status__c</controllingField>
            <picklistValues>
                <fullName>Carry In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Charges_After_Tax__c</fullName>
        <formula>( (Service_Charges__c - Service_Charges__c * Discount_in_Service_Charges__c ) + Service_Charges_Other__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Charges(After Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Charges_Other__c</fullName>
        <label>Misc. Service Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Charges__c</fullName>
        <label>Service Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Component_Amount_After_Tax__c</fullName>
        <formula>(Net_Basic_CC_Amount__c * Component_Tax_Rate_1__c ) + Net_Basic_CC_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Component Amount (After Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GenerateInvoice.cls
public class GenerateInvoice{

   public wrapperInvoice  WObj{get;set;}
 
    public GenerateInvoice() {
        
        //GetInvoiceDetails(InvId);
    }
    
    public void GetInvoiceDetails()
    {
      string InvId = ApexPages.CurrentPage().getParameters().get('id');
      Service_Request__c  SRObj = [Select id,Status__c,Service_Centre_City__r.Code__c,Component_Bill_No__c,Component_Charges__c,Discount_in_Component_Charges__c,Misc_Component_Charges__c,Misc_Component_Charges_Remark__c,Net_Basic_CC_Amount__c,Component_Tax_Rate_1__c,Total_Component_Amount_After_Tax__c,Grand_Total__c,Receiving_Date__c,Service_Bill_No__c,Service_Charge_Type__c,Service_Charges__c,Service_Charges_Other__c,Misc_Service_Charges_Remark__c,Discount_in_Service_Charges__c,Net_Basic_SC_Amount__c,Service_Charges_After_Tax__c from Service_Request__c where id =:InvId];
      if(SRObj.Status__c == 'Closed')
      {
          List<Invoice_No__c> lstInv = [SELECT id,Invoive_Number__c,Service_Request__c,Full_Invoice_No__c from Invoice_No__c where Service_Request__c =: SRObj.id];
          if(lstInv.size()<=0)
          {
            Invoice_No__c objINV = [SELECT id,Invoive_Number__c,Service_Request__c,Full_Invoice_No__c from Invoice_No__c ORDER BY Id DESC LIMIT 1];
            integer iNo = integer.valueof(objINV.Invoive_Number__c)+1;
            
            
            //Get logged in user stock point
              List<Stock_Point__c> lstSP = [select id,name from Stock_Point__c where CreatedById =: Userinfo.getUserId()];
            
            //string sFullInvoiceNo = '13-14/SC/'+ SRObj.Service_Centre_City__r.Code__c + '/' + iNo ;
            string sStockPoint = '';
            if(lstSP.size()>0)
            {
               sStockPoint = lstSP[0].Name.SubString(0,3);
            }
            
            string sFullInvoiceNo = '13-14/SC/'+ sStockPoint + '/' + iNo ;
            //WObj = new wrapperInvoice(SRObj ,integer.valueof(objINV.Invoive_Number__c)+1);
            WObj = new wrapperInvoice(SRObj ,sFullInvoiceNo);
            
            //Insert new record in invoice table
            Invoice_No__c objI = new Invoice_No__c();
            objI.Service_Request__c = InvId;
            objI.Full_Invoice_No__c = sFullInvoiceNo ;
            Insert objI ;
          }
          else
          {
            //Invoice already created
             //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Invoice already generated for this service request.');
             WObj = new wrapperInvoice(SRObj ,lstInv[0].Full_Invoice_No__c);
          }
      }
    }
    
    
    public class wrapperInvoice{
       public Service_Request__c SRObj{get;set;}
       public string InvoiceNo{get;set;}
       
       public wrapperInvoice(Service_Request__c sr,string sInvNo)
       {
         SRObj = sr;
         InvoiceNo = sInvNo;
       }
    
    }
}