src/objects/Marketing_Material__c.object
<CustomObject>
    <fields>
        <fullName>Contents__c</fullName>
        <label>Contents</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>PoP-Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Leaflet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Z cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Dangler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP-Collaterals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing Material</label>
    <nameField>
        <label>Marketing Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Material</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MM_Request_Details__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Quantity__c</fullName>
        <label>Approved Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Requests__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Requests</label>
        <referenceTo>Partner_Service_Request__c</referenceTo>
        <relationshipLabel>MM Request Details</relationshipLabel>
        <relationshipName>MM_Request_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MM Request Details</label>
    <nameField>
        <displayFormat>MM - {0000000}</displayFormat>
        <label>MM Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MM Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_Of_Request__c</fullName>
        <label>Type Of Request</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding – Ageing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Statement (Overall)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque Bounce Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Returns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Financial Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Our product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services / Sales Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Leaflet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Z Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Danglers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Posters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Collaterals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Certificates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Requests</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <label>Category Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Description__c</fullName>
        <label>Category Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Service_Request_Test_Class.cls
@istest
private class Service_Request_Test_Class
{ 
	static Schema.DescribeSObjectResult d = Schema.SObjectType.Partner_Service_Request__c;
	static Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
	static Schema.RecordTypeInfo rtByName =  rtMapByName.get('Marketing Material Request');
	static Id mmrrectypeid = rtByName.getRecordTypeId();
		
    static testMethod void Service_Request_Test()
    {
        ApexPages.StandardController controller2;
        //Querying the record type
        //RecordType servReqsRecordType = [Select Id,Name from RecordType Where sObjectType = 'Partner_Service_Request__c' And Name = 'Marketing Material Request' limit 1];
 
        Marketing_Material__c mm = new Marketing_Material__c();
        mm.Name = 'test Brochure 001';
        mm.Contents__c = 'Contents 001';
        mm.Description__c = 'Description 001';
        mm.Language__c = 'Language 001';
        mm.Size__c = 'Size 001';
        mm.Type__c  = 'Brochure';
        insert mm;
        
        PageReference pageRef = Page.PartnerRequestPage;
        System.debug('=====pageRef ========'+pageRef);
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('mode', 'NEW');
        ApexPages.currentPage().getParameters().put('reqType', 'PoP-Brochure');
        ApexPages.currentPage().getParameters().put('RecordType', mmrrectypeid);
        ApexPages.currentPage().getParameters().put('reqType','Brochure');
        PartnerRequestController prController = new PartnerRequestController();
        
        prController.save();
        
        
        pageRef = Page.PartnerRequestPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('mode', 'NEW');
        ApexPages.currentPage().getParameters().put('reqType', 'DealerCertificate');
        ApexPages.currentPage().getParameters().put('RecordType', mmrrectypeid);
        
        prController = new PartnerRequestController();
        prController.save();
        prController.getPartnerRequest();
        prController.getReqDetails();
        prController.getPartnerReqs();
        
       // Partner_Service_Request__c  psr = [Select Id From Partner_Service_Request__c ];
        Partner_Service_Request__c psr1 = new Partner_Service_Request__c(
            Type_Of_Request__c = 'Bills',
            Status__c = 'open',
            Remarks__c = 'a'
        );
        insert psr1;
        
        MM_Request_Details__c mmObj =  new MM_Request_Details__c(
            Approved_Quantity__c = 1000,
            Service_Requests__c = psr1.id
        );
        insert mmObj;
        
        pageRef = Page.PartnerRequestPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('mode', 'EDIT');
        ApexPages.currentPage().getParameters().put('reqType', 'PoP-Brochure');
        ApexPages.currentPage().getParameters().put('RecordType', mmrrectypeid);
        ApexPages.currentPage().getParameters().put('prId', psr1.Id);
        
        prController = new PartnerRequestController();
        prController.save();
        
        pageRef = Page.PartnerRequestPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('mode', 'EDIT');
        ApexPages.currentPage().getParameters().put('reqType', 'PoP-Brochure');
        ApexPages.currentPage().getParameters().put('RecordType', mmrrectypeid);
        ApexPages.currentPage().getParameters().put('prId', psr1.Id);
        
        //prController = new PartnerRequestController();
        prController.save();
        
        prController.getMode();
        prController.getDisplayType();
      //prController.getMmType();
        prController.getPrId();
        prController.cancel();
        prController.cancelEdit();
        prController.addRows();
        
        PartnerRequestController.ReqDetail reqDet = new PartnerRequestController.ReqDetail();
        PartnerRequestController.PartnerRequest parReq = new PartnerRequestController.PartnerRequest();
        prController.getPartnerRequest();
    }
    
    static testMethod void Service_Request_Call_Type_Test()
    {
        ApexPages.StandardController controller2;
        
        ServiceRequestsCallType srCallTyp2 = new ServiceRequestsCallType(controller2);
        //Querying the record type
        //RecordType servReqsRecordType = [Select Id,Name from RecordType Where sObjectType = 'Partner_Service_Request__c' And Name = 'Marketing Material Request' limit 1];
        
        ServiceRequestsCallType srCalltyp = new ServiceRequestsCallType();
        
        PageReference pageRef = Page.PartnerRequestPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('RecordType', mmrrectypeid);
        
        srCalltyp.goToMarketingMaterialPage();
 
    }
    public static testMethod void getCoverage(){
           Product__c prd = new Product__c(
            Category_Code__c = 'wer',
            Category_Description__c = 'cc',
            Product_Description__c = 'kk',
            name = 'ee'
        );
        insert prd;
        ApexPages.currentPage().getParameters().put('prId',prd.id);
        ApexPages.currentPage().getParameters().put('mode','EDIT');
       
        PartnerRequestController.ReqDetail  objwrp = new PartnerRequestController.ReqDetail();  
        List<PartnerRequestController.PartnerRequest> lstPart ;
       // prController.setReqDetails(lstPart);
    }
}