src/objects/Partner_Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_Of_Request__c</fullName>
        <label>Type Of Request</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding – Ageing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Statement (Overall)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque Bounce Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Returns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Financial Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Our product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services / Sales Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Leaflet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Z Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Danglers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Posters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - Collaterals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PoP - CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Certificates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Requests</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Trg_ServiceRequestsShare_TestClass.cls
@istest
private class Trg_ServiceRequestsShare_TestClass
{
    static testMethod void test1()
    {
        Map<String,String> rtMap = new Map<String,String>();
        List<RecordType> rtList = new List<RecordType>();
        
        rtList = [Select Id,Name From RecordType Where Name = : 'Financial Service Request' or Name = : 'Marketing Material Request' or Name = : 'General Information / Complaints' or Name = : 'Product Complaint'];
        
        for(RecordType rt : rtList)
            rtMap.put(rt.Name,rt.Id);
        
        Partner_Service_Request__c psr = new Partner_Service_Request__c();
        
        psr.Type_Of_Request__c = 'Bills';
        psr.Status__c = 'Open';
        psr.Remarks__c = 'test';
        psr.RecordTypeId = rtMap.get('Financial Service Request');
        insert psr;
        
        Partner_Service_Request__c psr1 = new Partner_Service_Request__c();
        
        psr1.Type_Of_Request__c = 'PoP-Leaflet';
        psr1.Quantity__c = 1;
        psr1.Remarks__c = 'test';
        psr1.RecordTypeId = rtMap.get('Marketing Material Request');
        insert psr1;
        
        Partner_Service_Request__c psr2 = new Partner_Service_Request__c();      
        
        psr2.Status__c = 'Open';
        psr2.Remarks__c = 'test';
        psr2.RecordTypeId = rtMap.get('General Information / Complaints');
        insert psr2;
        
        Partner_Service_Request__c psr3 = new Partner_Service_Request__c();      
        
        psr3.Status__c = 'Open';
        psr3.Remarks__c = 'test';
        psr3.RecordTypeId = rtMap.get('Product Complaint');
        insert psr3;
    }
}