src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Book__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseStandardPrice</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/priceBookEntryPageComponentCon.cls
public class priceBookEntryPageComponentCon{
    public List<Price_Book_Entry__c> pbeList {get;set;}
    public Product__c product {get;set;}
    
    public priceBookEntryPageComponentCon(ApexPages.StandardController controller){
        this.product = (Product__c)controller.getRecord();
        
        system.debug('Product======'+product);
        generatePBEList() ;   
    }  
    
    public void generatePBEList(){
        pbeList = new List<Price_Book_Entry__c>();
        if(product!= null)
            pbeList = [SELECT IsActive__c,  Name__c, Name, OwnerId,Price_Book__r.Name, Price_Book__r.IsStandard__c, PriceBook__c, Price_Book__c, 
                       Product__c, Product_Code__c, Id, UnitPrice__c, UseStandardPrice__c FROM Price_Book_Entry__c
                       WHERE Product__c =:product.Id  and Price_Book__c!= null and Price_Book__r.IsStandard__c = false];
        system.debug('pbeList==='+pbeList);           
    }
    
    public pageReference editPBE(){
        String pbeId = ApexPages.currentPage().getParameters().get('pbeId');   
        pageReference page = new pageReference('/apex/editPricBookEntryList?pid='+product.id+'&pbeId='+pbeId);
        page.setRedirect(true);
        return page;
    }
    public pageReference viewPBE(){
        String pbeId = ApexPages.currentPage().getParameters().get('pbeId');   
        pageReference page = new pageReference('/'+pbeId);
        page.setRedirect(true);
        return page;    
    }
    
    public pageReference deletePBE(){
        String pbeId = ApexPages.currentPage().getParameters().get('pbeId');  
        Price_Book_Entry__c pbe = new Price_Book_Entry__c();
        if(pbeId != null && pbeId != '')
            pbe = [Select id from Price_Book_Entry__c where id=:pbeId] ;
        if(pbe != null){
            try{
                delete pbe;
            }catch(Exception e){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                return null;
            }
        }    
        return null;
    }
    
}