src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <label>Category Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Description__c</fullName>
        <label>Category Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Price__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book Entry</label>
        <referenceTo>Price_Book_Entry__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Standard Price</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Standard Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Price</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreatePriceBookEntryCon_Test.cls
@isTest
public class CreatePriceBookEntryCon_Test{
    public static testMethod void myunitTest(){
        Product__c prd = new Product__c(
            Category_Code__c = 'wer',
            Category_Description__c = 'cc',
            Product_Description__c = 'kk',
            name = 'ee'
        );
        insert prd;
        
        Price_Books__c  pb = new Price_Books__c (
            Description__c = 'test',
            IsActive__c = true,
            Name = 'Tests'
            //CurrencyIsoCode = 'USD'
         );
        insert pb;
        
        Price_Books__c  pb1 = new Price_Books__c (
            Description__c = 'test',
            IsActive__c = true,
            IsStandard__c = true,
            Name = 'Tests'
           // CurrencyIsoCode = 'USD'
         );
        insert pb1;
        
      Standard_Price__c spb = new Standard_Price__c (
           Products__c = prd.id,
           Conversion_Rate__c = 122,
           Standard_Price__c = 23
         //  CurrencyIsoCode = 'USD'
       );
       insert spb;
       
       Standard_Price__c spb1 = new Standard_Price__c (
           Products__c = prd.id,
           Conversion_Rate__c = 122,
           Standard_Price__c = 23
          // CurrencyIsoCode = 'INR'
       );
       insert spb1;
       
      Price_Book_Entry__c pbe = new Price_Book_Entry__c (
           Product__c = prd.id,
           Price_book__c = pb.id
           //CurrencyIsoCode = 'USD'
         );
       insert pbe;
       
       Price_Book_Entry__c pbe1 = new Price_Book_Entry__c (
           Product__c = prd.id,
           Price_book__c = pb1.id
           //CurrencyIsoCode = 'USD'
         );
       insert pbe1;
       
        ApexPages.currentPage().getParameters().put('id',prd.id);
        ApexPages.StandardController std = new ApexPages.StandardController(prd);
        CreatePriceBookEntryCon cpbec = new CreatePriceBookEntryCon(std);
        CreatePriceBookEntryCon.priceBookWrapper wrap = new CreatePriceBookEntryCon.priceBookWrapper(pb1,spb1,'test');
        CreatePriceBookEntryCon.priceBookWrapper wrap1 = new CreatePriceBookEntryCon.priceBookWrapper(pb1,true);
        cpbec.onSelect();
        cpbec.finalWrapperList = new List<CreatePriceBookEntryCon.priceBookWrapper>();
        cpBec.pbWrapperList = new List<CreatePriceBookEntryCon.priceBookWrapper>();
        cpbec.finalWrapperList.add(wrap1);
        wrap1.Selected = true;
        cpbec.onSelect();
        cpbec.doSave();
        cpbec.doCancel();
        cpbec.doSaveAndMore(); 
        
        ApexPages.currentPage().getParameters().put('pid',prd.id);
        editPriceBookEntryCon epbe = new editPriceBookEntryCon(std);
        editPriceBookEntryCon.priceBookWrapper wrap2= new editPriceBookEntryCon.priceBookWrapper(pbe, 100);
        epbe.pbeList = new List<editPriceBookEntryCon.priceBookWrapper>();
        epbe.doSave();
        wrap2.Selected = true;
        epbe.pbeList.add(wrap2);
        epbe.doSave();
               
        epbe.doCancel();
        
        
        priceBookEntryPageComponentCon pbecon = new priceBookEntryPageComponentCon(std); 
        ApexPages.currentPage().getParameters().put('pbeId',pbe1.id);
        pbecon.editPBE();
        pbecon.viewPBE();  
        pbecon.deletePBE();  
    
    }
}