src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Price__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book Entry</label>
        <referenceTo>Price_Book_Entry__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Standard Price</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Standard Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Price</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public class ProductController {
    
    public Product__c prodRec { get; set; }
    public List<Price_Book_Entry__c> stdPriceList {get; set;}
    public String productName {get;set;}
    Standard_Price__c stdPrice ;
    String pbeid;
    String pid;
    String stdid;
    
   public productController(ApexPages.StandardController controller){
        stdPrice = new Standard_Price__c();
        stdid = ApexPages.currentPage().getParameters().get('id');
        if(stdid  != null && stdid != ''){    
            stdPrice = [Select id, Name, Price_Book_Entry__c, Products__c, Products__r.Name from Standard_Price__c where id=:stdid ];
            productName = stdPrice.Products__r.Name;
        }    
        pid = ApexPages.currentPage().getParameters().get('pid');
        String type = ApexPages.currentPage().getParameters().get('type');
        if(stdid != null && stdid != '' )
            type = 'edit';    
        stdPriceList = new List<Price_Book_Entry__c>();
        if(pid != null && pid != ''){
            prodRec = [select Name from Product__c where id = :pid];
            productName = prodRec.Name;
        }
        List<Price_Books__c> pbList = [select Name, isStandard__c from Price_Books__c where isStandard__c = true];
        if(pbList != null && pbList.size() == 0) {
            system.debug('pbList==='+pbList);
            Price_Books__c stdpb = new Price_Books__c(Name = 'Standard Price Book', isStandard__c = true);
            pbList.add(stdpb);
            insert pbList;
        }
        List<Price_Book_Entry__c> spList = new List<Price_Book_Entry__c>();
        if(stdPrice.Price_Book_Entry__c != null){
            
             spList = [select CurrencyIsoCode, Conversion_Rate__c, UnitPrice__c, IsActive__c , Product__r.Name
                       from Price_Book_Entry__c where id = :stdPrice.Price_Book_Entry__c];
                   
        }
       else  { 
             if(pid != null && pid != '' && pbList != null && pbList.size() > 0)             
                 spList = [select CurrencyIsoCode, Conversion_Rate__c, UnitPrice__c, IsActive__c, Product__r.Name 
                          from Price_Book_Entry__c where Product__c = :pid
                          and Price_Book__c =: pbList[0].id];
       } 
        if(type != null && type.equals('new')) {
            Set<String> curncySet = new Set<String>();
            for(Price_Book_Entry__c sp :spList) {
                curncySet.add(sp.CurrencyIsoCode);
            }
            
            for(CurrencyType ct :[Select c.IsoCode, c.IsActive, c.ConversionRate From CurrencyType c where isActive = true]) {
                if(!curncySet.contains(ct.IsoCode)) {
                    stdPriceList.add(new Price_Book_Entry__c(
                        CurrencyIsoCode = ct.IsoCode, 
                        Product__c = pid,
                        Conversion_Rate__c = ct.ConversionRate,
                        Price_Book__c = pbList[0].id,
                        UnitPrice__c = 0.0,
                        isActive__c = true
                    ));
                }
            }
        }
        
        if(type != null && type.equals('edit')) {
            stdPriceList.addAll(spList);
        }
   }
    
    public productController() {
        
    }
    
    public pageReference doCancel(){
        pageReference page;
        if(stdid != null && stdid  != '')
            page = new PageReference('/'+stdPrice.Products__c);    
        else
            page = new PageReference('/'+pid);
       
        page.setRedirect(true);
        return page;
    }
    
    public PageReference doSave() {
        List<Price_Book_Entry__c> listToInsert = new List<Price_Book_Entry__c>();
        for(Price_Book_Entry__c sp :stdPriceList) {
            
            if(sp.id == null && sp.UnitPrice__c!= null && sp.UnitPrice__c > 0) {
                listToInsert.add(sp);
            } else if(sp.id != null && (sp.UnitPrice__c == null || sp.UnitPrice__c <= 0)) {
                ApexPages.addMessage(new Apexpages.Message(ApexPAges.Severity.ERROR, 'Standard Price cannot be blank'));
                return null;
            }  else if(sp.id != null) {
                listToInsert.add(sp);
            }
        }
        if(listToInsert != null && listToInsert.size() > 0)
            upsert listToInsert;
        if(stdid != null && stdid != '')
            return new PageReference('/'+stdPrice.Products__c);    
        else
            return new PageReference('/'+pid);
    }
}