src/objects/Price_Book__c.object
<CustomObject>
    <description>A detailed list of all the products with the respective price books which will be uploaded through external utilities and will be later used by the business.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <label>Price Books AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Book__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Price_Books__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Price Book Entry</relationshipLabel>
        <relationshipName>Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseStandardPrice</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Book Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Entry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Books__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStandard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStandard</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Books</label>
    <nameField>
        <label>Price Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Price__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book Entry</label>
        <referenceTo>Price_Book_Entry__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Standard Price</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Standard Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Price</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/editPriceBookEntryCon.cls
public class editPriceBookEntryCon{
    String pid;
    String pbeid;
    public List<priceBookWrapper> pbeList {get;set;}
    Map<String, Double> stPriceMap ;
    
    public editPriceBookEntryCon(ApexPages.StandardController controller){
        pid = ApexPages.CurrentPage().getParameters().get('pid'); 
        pbeid = ApexPages.CurrentPage().getParameters().get('pbeid'); 
        createPiceMap();
        createPriceBookList();
          
    }
    
    public void createPiceMap(){
        stPriceMap = new Map<String, Double>();
        if(pid != null && pid != ''){
            for(Standard_Price__c s : [SELECT Active__c, Conversion_Rate__c,CurrencyIsoCode, Products__c, 
                                        Id, Standard_Price__c, Name FROM Standard_Price__c where Products__c=: pid]){
                stPriceMap.Put(s.CurrencyIsoCode,s.Standard_Price__c);                                
            }
            if(stPriceMap == null || stPriceMap.size()== 0){
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'There is no standard price record.');
                ApexPages.addMessage(myMsg);
            }
        }
    }
    
    public void createPriceBookList(){
          pbeList =   new List<priceBookWrapper>();
          if(pid != null && pid != ''){
              List<Price_Book_Entry__c> pbeTempList = new List<Price_Book_Entry__c>();
              if(pbeid != null && pbeid != ''){
                  pbeTempList = [SELECT CurrencyIsoCode, IsActive__c, LastModifiedDate, Name__c, 
                                OwnerId, PriceBook__c, Price_Book__r.Name, Price_Book__c, Product__c , Product__r.Name, Product_Code__c, 
                                Id, UnitPrice__c, UseStandardPrice__c FROM Price_Book_Entry__c where id =:pbeid ];
              }
              else{
                  pbeTempList = [SELECT CurrencyIsoCode, IsActive__c, LastModifiedDate, Name__c, 
                                OwnerId, PriceBook__c, Price_Book__r.Name, Price_Book__c, Product__c , Product__r.Name, Product_Code__c, 
                                Id, UnitPrice__c, UseStandardPrice__c FROM Price_Book_Entry__c where id =:pid
                                and Price_Book__r.IsStandard__c = false];
              }
              if(pbeTempList != null && pbeTempList.size() > 0){
                  for(Price_Book_Entry__c  p : pbeTempList){
                      if(stPriceMap != null && stPriceMap.size() > 0 ) {
                          if(stPriceMap.containsKey(p.CurrencyIsoCode))
                              pbeList.add(new priceBookWrapper(p,stPriceMap.get(p.CurrencyIsoCode)));    
                      }
                  }   
              }     
          }
    }
    
     public pageReference doCancel(){
        pageReference page = new PageReference('/'+pId);
        page.setRedirect(true);
        return page;
    }

    
    public pageReference doSave(){
        if(pbeList != null && pbeList.size() > 0){
            List<Price_Book_Entry__c> pbeTempList = new List<Price_Book_Entry__c>();
            Boolean flag = false;
            for(priceBookWrapper p : pbeList){
                p.pbe.UseStandardPrice__c = p.Selected;
                if(p.pbe.UnitPrice__c == null || p.pbe.UnitPrice__c == 0)
                    if(!p.Selected){
                        flag = true;
                        break;
                    }
                
                if(p.Selected)
                    p.pbe.UnitPrice__c = p.stdPrice ;
                   
                pbeTempList.add(p.pbe);
        }    
        
        if(flag){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'UnitPrice can not be blank .');
            ApexPages.addMessage(myMsg);
            return null;
        }
        else{
            if(pbeTempList != null ){
                try{
                    update pbeTempList ; 
                }Catch(Exception e){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
                    ApexPages.addMessage(myMsg);
                    return null;   
                }   
            }
        }
        PageReference page =  new PageReference('/'+pid);
        page.setRedirect(true);
        return page;
        }
        else{
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'There is no record.');
            ApexPages.addMessage(myMsg);
            return null; 
        }
     }
       
    
    
     public class priceBookWrapper{
        public Price_Book_Entry__c pbe{get;set;}
        public Boolean selected {get;set;}
        public Double stdPrice {get;set;}    
        
        public priceBookWrapper(Price_Book_Entry__c pb,Double sp){
            this.pbe= pb;
            this.selected = false;
            this.stdPrice = sp;
        }
    }    
}