src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <label>Category Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Description__c</fullName>
        <label>Category Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Price__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Standard Price</relationshipLabel>
        <relationshipName>Standard_Price</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Standard Price</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Standard Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Price</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProductController_Test.cls
@isTest
public class ProductController_Test{
    public static testMethod void getCoverage(){
    
        Product__c prd = new Product__c (
            Name = 'test',
            Category_Code__c = 'test1',
            Category_Description__c = 'test2',
            Product_Description__c = 'test3',    
            Product_Code__c = 'test4'
        );
        insert prd;
        
        Standard_Price__c sp = new Standard_Price__c(
            Products__c = prd.id,
            Standard_Price__c = 0,
            Active__c = true
        );
        insert sp;
        
    ApexPages.currentPage().getParameters().put('Id',sp.Id);
    ApexPages.StandardController con = new  ApexPages.StandardController(sp);
    ProductController pc = new ProductController(con);
    
    pc.doSave();
    pc.doCancel();
    
    ApexPages.currentPage().getParameters().put('Id',null);    
    ApexPages.currentPage().getParameters().put('pid',prd.id);
    ApexPages.currentPage().getParameters().put('type','new');
    pc = new ProductController(con);
    pc.doSave();
    pc.doCancel();
    
    
    
       
        
    }
}