src/objects/Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTENDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLOCATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReOpen</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseOverrideCtrl.cls
public class CaseOverrideCtrl {
    Service_Request__c srRecord;
    
    public CaseOverrideCtrl(ApexPages.StandardController ctrl) {
        srRecord = (Service_Request__c)ctrl.getRecord();
        
    }
    
    public PageReference srRedirect() {
        srRecord = [select Status__c from Service_Request__c where id = :srRecord.id];
        User u = [select Profile.Name from User where id = :UserInfo.getUserId()];
        
        if(srRecord.Status__c != null && srRecord.Status__c.equals('Closed') && !u.Profile.Name.equals('System Administrator')) {
            PageReference pgRef = new PageReference('/apex/CaseDetail?id=' + srRecord.id);
            pgRef.setRedirect(true);
            return pgRef;
        } else {
            PageReference pgRef = new PageReference('/' + srRecord.id + '?nooverride=1');
            pgRef.setRedirect(true);
            return pgRef;
        }
    }
}