src/objects/Stock_Point__c.object
<CustomObject>
    <description>Master of all Service Centers, Service Engineers</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To Branch</label>
        <referenceTo>Stock_Point__c</referenceTo>
        <relationshipLabel>Stock Points (Related To Branch)</relationshipLabel>
        <relationshipName>Stock_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Point</label>
    <nameField>
        <label>Stock Point No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Points</pluralLabel>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Point__c</fullName>
        <label>Stock Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCreateSharesForBranchUsers.cls
@isTest
public class TestCreateSharesForBranchUsers {
    
    static testmethod void testCrSharesBrUsersMethod() { 
       Profile p = [Select ID from PROFILE where name = 'Service Center'] ;
       
       User u1 = new User(alias = 'standt', email='standarduser@testorg.com',
           emailencodingkey='UTF-8', lastname='Testing',
           languagelocalekey='en_US',
           localesidkey='en_US', profileid  =  p.id,
           timezonesidkey='America/Los_Angeles',
           username='standarduser12@testorg.com');
           insert u1;
           
        ID stRecordType;
        ID stRecordType1;
        for(RecordType rt : [SELECT Id, Name  FROM RecordType  WHERE SObjectType = 'Stock_Point__c' AND Name =: 'Branch']) {
            stRecordType = rt.Id;            
        } 
        for(RecordType rt1 : [SELECT Id, Name  FROM RecordType  WHERE SObjectType = 'Stock_Point__c' AND Name =: 'Service Center']) {
            stRecordType1 = rt1.Id;            
        }       
        Stock_Point__c spObj = new Stock_Point__c(Name = 'AMIT KUMAR CHAURSIYA',Region__c = 'CENTRAL',
                                                    RecordTypeId = stRecordType );
        insert spObj;  
        spObj.OwnerId = u1.id;
        update spObj;
              
        Stock_Point__c spObj1 = new Stock_Point__c(Name = 'AMIT KUMAR ',Region__c = 'NORTH',
                                                    RecordTypeId = stRecordType );
        insert spObj1;
        spObj1.OwnerId = u1.id;
        update spObj1;
        
        Stock_Point__c spObj2 = new Stock_Point__c(Name = 'AMIT CHAURSIYA',Region__c = 'SOUTH',
                                                    RecordTypeId = stRecordType1, Related_To_Branch__c = spObj.Id);
        insert spObj2;
        spObj2.Related_To_Branch__c = spObj1.Id;
        //spObj2.Region__c = 'WEST';
        update spObj2;
        
              
    }
}